#Code generated by RScriptGenerator.java


SVMEnsemble_11_howtopredict<-function(SELECTION,test_normal,test_index,y,yName,d11,created11,model11,svm11,d12,created12,model12,svm12,d13,created13,model13,svm13,d21,created21,model21,svm21,d22,created22,model22,svm22,d23,created23,model23,svm23,d31,created31,model31,svm31,d32,created32,model32,svm32,d33,created33,model33,svm33,d41,created41,model41,svm41,d42,created42,model42,svm42){

if(DEBUG){
	print(test_index)
	print(rownames(test_normal)[test_index])
}

#get PC1 value.
tpc1<-y[which(yName==rownames(test_normal)[test_index])]
prd<-0 

if(DEBUG) print(tpc1)


#RADs<-c(100,200,300,400)
RADs<-c(abs(max(d11$auc)-min(d11$auc))/2,abs(max(d12$auc)-min(d12$auc))/2,abs(max(d13$auc)-min(d13$auc))/2,abs(max(d21$auc)-min(d21$auc))/2,abs(max(d22$auc)-min(d22$auc))/2,abs(max(d23$auc)-min(d23$auc))/2,abs(max(d31$auc)-min(d31$auc))/2,abs(max(d32$auc)-min(d32$auc))/2,abs(max(d33$auc)-min(d33$auc))/2,abs(max(d41$auc)-min(d41$auc))/2,abs(max(d42$auc)-min(d42$auc))/2)
if(DEBUG) print(paste('rad11','rad12','rad13','rad21','rad22','rad23','rad31','rad32','rad33','rad41','rad42',sep=' '))
if(DEBUG) print(RADs)
RADs<-sort(RADs)
radius<-RADs[1]
if(DEBUG) print(radius)
RAD<-radius
nbr11<-0
pred11<-0
radius11<-0
bsc11<-0 #block spearman correlation
if(created11){
	pred11 = predict(svm11, test_normal[test_index,])
	pred11 = as.numeric(pred11)
	tmp11<-rbind(d11,c(pred11,tpc1))
	tmp11<-as.data.frame(tmp11)
	dist11<-dist(tmp11, method = "euclidean")
	dist11<-as.matrix(dist11)
	tmp111<-t(rbind(model11[,-ncol(model11)],test_normal[test_index,-ncol(test_normal)])) #transpose
	cor11<-cor(tmp111, method = c('spearman'))
	bsc11<-sum(cor11[1:nrow(cor11)-1,ncol(cor11)])/nrow(d11)
}
mc11<-0
if(created11) {
	found<-which(dist11[1:nrow(dist11)-1,ncol(dist11)]<=RAD)
	neighbors11<-rownames(dist11)[found]
	nbr11<-length(found)
	if(nbr11>0){
		corIndx<-which(rownames(cor11) %in% neighbors11)   #we will look at the last column of the matrix. So matching by rownames
		mc11<-mean(cor11[corIndx,ncol(cor11)])
		if(DEBUG){
			print("svm11")
			print(neighbors11)
			print(rownames(cor11)[corIndx])
		}
	} else {
		mc11<-0
	}
}
nbr12<-0
pred12<-0
radius12<-0
bsc12<-0 #block spearman correlation
if(created12){
	pred12 = predict(svm12, test_normal[test_index,])
	pred12 = as.numeric(pred12)
	tmp12<-rbind(d12,c(pred12,tpc1))
	tmp12<-as.data.frame(tmp12)
	dist12<-dist(tmp12, method = "euclidean")
	dist12<-as.matrix(dist12)
	tmp121<-t(rbind(model12[,-ncol(model12)],test_normal[test_index,-ncol(test_normal)])) #transpose
	cor12<-cor(tmp121, method = c('spearman'))
	bsc12<-sum(cor12[1:nrow(cor12)-1,ncol(cor12)])/nrow(d12)
}
mc12<-0
if(created12) {
	found<-which(dist12[1:nrow(dist12)-1,ncol(dist12)]<=RAD)
	neighbors12<-rownames(dist12)[found]
	nbr12<-length(found)
	if(nbr12>0){
		corIndx<-which(rownames(cor12) %in% neighbors12)   #we will look at the last column of the matrix. So matching by rownames
		mc12<-mean(cor12[corIndx,ncol(cor12)])
		if(DEBUG){
			print("svm12")
			print(neighbors12)
			print(rownames(cor12)[corIndx])
		}
	} else {
		mc12<-0
	}
}
nbr13<-0
pred13<-0
radius13<-0
bsc13<-0 #block spearman correlation
if(created13){
	pred13 = predict(svm13, test_normal[test_index,])
	pred13 = as.numeric(pred13)
	tmp13<-rbind(d13,c(pred13,tpc1))
	tmp13<-as.data.frame(tmp13)
	dist13<-dist(tmp13, method = "euclidean")
	dist13<-as.matrix(dist13)
	tmp131<-t(rbind(model13[,-ncol(model13)],test_normal[test_index,-ncol(test_normal)])) #transpose
	cor13<-cor(tmp131, method = c('spearman'))
	bsc13<-sum(cor13[1:nrow(cor13)-1,ncol(cor13)])/nrow(d13)
}
mc13<-0
if(created13) {
	found<-which(dist13[1:nrow(dist13)-1,ncol(dist13)]<=RAD)
	neighbors13<-rownames(dist13)[found]
	nbr13<-length(found)
	if(nbr13>0){
		corIndx<-which(rownames(cor13) %in% neighbors13)   #we will look at the last column of the matrix. So matching by rownames
		mc13<-mean(cor13[corIndx,ncol(cor13)])
		if(DEBUG){
			print("svm13")
			print(neighbors13)
			print(rownames(cor13)[corIndx])
		}
	} else {
		mc13<-0
	}
}
nbr21<-0
pred21<-0
radius21<-0
bsc21<-0 #block spearman correlation
if(created21){
	pred21 = predict(svm21, test_normal[test_index,])
	pred21 = as.numeric(pred21)
	tmp21<-rbind(d21,c(pred21,tpc1))
	tmp21<-as.data.frame(tmp21)
	dist21<-dist(tmp21, method = "euclidean")
	dist21<-as.matrix(dist21)
	tmp211<-t(rbind(model21[,-ncol(model21)],test_normal[test_index,-ncol(test_normal)])) #transpose
	cor21<-cor(tmp211, method = c('spearman'))
	bsc21<-sum(cor21[1:nrow(cor21)-1,ncol(cor21)])/nrow(d21)
}
mc21<-0
if(created21) {
	found<-which(dist21[1:nrow(dist21)-1,ncol(dist21)]<=RAD)
	neighbors21<-rownames(dist21)[found]
	nbr21<-length(found)
	if(nbr21>0){
		corIndx<-which(rownames(cor21) %in% neighbors21)   #we will look at the last column of the matrix. So matching by rownames
		mc21<-mean(cor21[corIndx,ncol(cor21)])
		if(DEBUG){
			print("svm21")
			print(neighbors21)
			print(rownames(cor21)[corIndx])
		}
	} else {
		mc21<-0
	}
}
nbr22<-0
pred22<-0
radius22<-0
bsc22<-0 #block spearman correlation
if(created22){
	pred22 = predict(svm22, test_normal[test_index,])
	pred22 = as.numeric(pred22)
	tmp22<-rbind(d22,c(pred22,tpc1))
	tmp22<-as.data.frame(tmp22)
	dist22<-dist(tmp22, method = "euclidean")
	dist22<-as.matrix(dist22)
	tmp221<-t(rbind(model22[,-ncol(model22)],test_normal[test_index,-ncol(test_normal)])) #transpose
	cor22<-cor(tmp221, method = c('spearman'))
	bsc22<-sum(cor22[1:nrow(cor22)-1,ncol(cor22)])/nrow(d22)
}
mc22<-0
if(created22) {
	found<-which(dist22[1:nrow(dist22)-1,ncol(dist22)]<=RAD)
	neighbors22<-rownames(dist22)[found]
	nbr22<-length(found)
	if(nbr22>0){
		corIndx<-which(rownames(cor22) %in% neighbors22)   #we will look at the last column of the matrix. So matching by rownames
		mc22<-mean(cor22[corIndx,ncol(cor22)])
		if(DEBUG){
			print("svm22")
			print(neighbors22)
			print(rownames(cor22)[corIndx])
		}
	} else {
		mc22<-0
	}
}
nbr23<-0
pred23<-0
radius23<-0
bsc23<-0 #block spearman correlation
if(created23){
	pred23 = predict(svm23, test_normal[test_index,])
	pred23 = as.numeric(pred23)
	tmp23<-rbind(d23,c(pred23,tpc1))
	tmp23<-as.data.frame(tmp23)
	dist23<-dist(tmp23, method = "euclidean")
	dist23<-as.matrix(dist23)
	tmp231<-t(rbind(model23[,-ncol(model23)],test_normal[test_index,-ncol(test_normal)])) #transpose
	cor23<-cor(tmp231, method = c('spearman'))
	bsc23<-sum(cor23[1:nrow(cor23)-1,ncol(cor23)])/nrow(d23)
}
mc23<-0
if(created23) {
	found<-which(dist23[1:nrow(dist23)-1,ncol(dist23)]<=RAD)
	neighbors23<-rownames(dist23)[found]
	nbr23<-length(found)
	if(nbr23>0){
		corIndx<-which(rownames(cor23) %in% neighbors23)   #we will look at the last column of the matrix. So matching by rownames
		mc23<-mean(cor23[corIndx,ncol(cor23)])
		if(DEBUG){
			print("svm23")
			print(neighbors23)
			print(rownames(cor23)[corIndx])
		}
	} else {
		mc23<-0
	}
}
nbr31<-0
pred31<-0
radius31<-0
bsc31<-0 #block spearman correlation
if(created31){
	pred31 = predict(svm31, test_normal[test_index,])
	pred31 = as.numeric(pred31)
	tmp31<-rbind(d31,c(pred31,tpc1))
	tmp31<-as.data.frame(tmp31)
	dist31<-dist(tmp31, method = "euclidean")
	dist31<-as.matrix(dist31)
	tmp311<-t(rbind(model31[,-ncol(model31)],test_normal[test_index,-ncol(test_normal)])) #transpose
	cor31<-cor(tmp311, method = c('spearman'))
	bsc31<-sum(cor31[1:nrow(cor31)-1,ncol(cor31)])/nrow(d31)
}
mc31<-0
if(created31) {
	found<-which(dist31[1:nrow(dist31)-1,ncol(dist31)]<=RAD)
	neighbors31<-rownames(dist31)[found]
	nbr31<-length(found)
	if(nbr31>0){
		corIndx<-which(rownames(cor31) %in% neighbors31)   #we will look at the last column of the matrix. So matching by rownames
		mc31<-mean(cor31[corIndx,ncol(cor31)])
		if(DEBUG){
			print("svm31")
			print(neighbors31)
			print(rownames(cor31)[corIndx])
		}
	} else {
		mc31<-0
	}
}
nbr32<-0
pred32<-0
radius32<-0
bsc32<-0 #block spearman correlation
if(created32){
	pred32 = predict(svm32, test_normal[test_index,])
	pred32 = as.numeric(pred32)
	tmp32<-rbind(d32,c(pred32,tpc1))
	tmp32<-as.data.frame(tmp32)
	dist32<-dist(tmp32, method = "euclidean")
	dist32<-as.matrix(dist32)
	tmp321<-t(rbind(model32[,-ncol(model32)],test_normal[test_index,-ncol(test_normal)])) #transpose
	cor32<-cor(tmp321, method = c('spearman'))
	bsc32<-sum(cor32[1:nrow(cor32)-1,ncol(cor32)])/nrow(d32)
}
mc32<-0
if(created32) {
	found<-which(dist32[1:nrow(dist32)-1,ncol(dist32)]<=RAD)
	neighbors32<-rownames(dist32)[found]
	nbr32<-length(found)
	if(nbr32>0){
		corIndx<-which(rownames(cor32) %in% neighbors32)   #we will look at the last column of the matrix. So matching by rownames
		mc32<-mean(cor32[corIndx,ncol(cor32)])
		if(DEBUG){
			print("svm32")
			print(neighbors32)
			print(rownames(cor32)[corIndx])
		}
	} else {
		mc32<-0
	}
}
nbr33<-0
pred33<-0
radius33<-0
bsc33<-0 #block spearman correlation
if(created33){
	pred33 = predict(svm33, test_normal[test_index,])
	pred33 = as.numeric(pred33)
	tmp33<-rbind(d33,c(pred33,tpc1))
	tmp33<-as.data.frame(tmp33)
	dist33<-dist(tmp33, method = "euclidean")
	dist33<-as.matrix(dist33)
	tmp331<-t(rbind(model33[,-ncol(model33)],test_normal[test_index,-ncol(test_normal)])) #transpose
	cor33<-cor(tmp331, method = c('spearman'))
	bsc33<-sum(cor33[1:nrow(cor33)-1,ncol(cor33)])/nrow(d33)
}
mc33<-0
if(created33) {
	found<-which(dist33[1:nrow(dist33)-1,ncol(dist33)]<=RAD)
	neighbors33<-rownames(dist33)[found]
	nbr33<-length(found)
	if(nbr33>0){
		corIndx<-which(rownames(cor33) %in% neighbors33)   #we will look at the last column of the matrix. So matching by rownames
		mc33<-mean(cor33[corIndx,ncol(cor33)])
		if(DEBUG){
			print("svm33")
			print(neighbors33)
			print(rownames(cor33)[corIndx])
		}
	} else {
		mc33<-0
	}
}
nbr41<-0
pred41<-0
radius41<-0
bsc41<-0 #block spearman correlation
if(created41){
	pred41 = predict(svm41, test_normal[test_index,])
	pred41 = as.numeric(pred41)
	tmp41<-rbind(d41,c(pred41,tpc1))
	tmp41<-as.data.frame(tmp41)
	dist41<-dist(tmp41, method = "euclidean")
	dist41<-as.matrix(dist41)
	tmp411<-t(rbind(model41[,-ncol(model41)],test_normal[test_index,-ncol(test_normal)])) #transpose
	cor41<-cor(tmp411, method = c('spearman'))
	bsc41<-sum(cor41[1:nrow(cor41)-1,ncol(cor41)])/nrow(d41)
}
mc41<-0
if(created41) {
	found<-which(dist41[1:nrow(dist41)-1,ncol(dist41)]<=RAD)
	neighbors41<-rownames(dist41)[found]
	nbr41<-length(found)
	if(nbr41>0){
		corIndx<-which(rownames(cor41) %in% neighbors41)   #we will look at the last column of the matrix. So matching by rownames
		mc41<-mean(cor41[corIndx,ncol(cor41)])
		if(DEBUG){
			print("svm41")
			print(neighbors41)
			print(rownames(cor41)[corIndx])
		}
	} else {
		mc41<-0
	}
}
nbr42<-0
pred42<-0
radius42<-0
bsc42<-0 #block spearman correlation
if(created42){
	pred42 = predict(svm42, test_normal[test_index,])
	pred42 = as.numeric(pred42)
	tmp42<-rbind(d42,c(pred42,tpc1))
	tmp42<-as.data.frame(tmp42)
	dist42<-dist(tmp42, method = "euclidean")
	dist42<-as.matrix(dist42)
	tmp421<-t(rbind(model42[,-ncol(model42)],test_normal[test_index,-ncol(test_normal)])) #transpose
	cor42<-cor(tmp421, method = c('spearman'))
	bsc42<-sum(cor42[1:nrow(cor42)-1,ncol(cor42)])/nrow(d42)
}
mc42<-0
if(created42) {
	found<-which(dist42[1:nrow(dist42)-1,ncol(dist42)]<=RAD)
	neighbors42<-rownames(dist42)[found]
	nbr42<-length(found)
	if(nbr42>0){
		corIndx<-which(rownames(cor42) %in% neighbors42)   #we will look at the last column of the matrix. So matching by rownames
		mc42<-mean(cor42[corIndx,ncol(cor42)])
		if(DEBUG){
			print("svm42")
			print(neighbors42)
			print(rownames(cor42)[corIndx])
		}
	} else {
		mc42<-0
	}
}
path<-"/Users/maju06/Documents/OSUMC/3C/"
if(DEBUG){
	blank<-c(1,2,3)
	blank<-as.data.frame(blank)
	colnames(blank)<-'x'
	blank$y<-c(1,2,3)
	blank<-as.data.frame(blank)
	if(!is.null(tmp11)){
		df11<-tmp11
		df11$label<-'old'
		df11$label[nrow(tmp11)]<-'new'
		df11<-as.data.frame(df11)
		p11<-ggplot(df11, aes(auc,pc1, color=factor(label))) + geom_point() + theme_classic()
	} else p11<-ggplot(blank, aes(x,y)) + theme_classic()
	if(!is.null(tmp12)){
		df12<-tmp12
		df12$label<-'old'
		df12$label[nrow(tmp12)]<-'new'
		df12<-as.data.frame(df12)
		p12<-ggplot(df12, aes(auc,pc1, color=factor(label))) + geom_point() + theme_classic()
	} else p12<-ggplot(blank, aes(x,y)) + theme_classic()
	if(!is.null(tmp13)){
		df13<-tmp13
		df13$label<-'old'
		df13$label[nrow(tmp13)]<-'new'
		df13<-as.data.frame(df13)
		p13<-ggplot(df13, aes(auc,pc1, color=factor(label))) + geom_point() + theme_classic()
	} else p13<-ggplot(blank, aes(x,y)) + theme_classic()
	if(!is.null(tmp21)){
		df21<-tmp21
		df21$label<-'old'
		df21$label[nrow(tmp21)]<-'new'
		df21<-as.data.frame(df21)
		p21<-ggplot(df21, aes(auc,pc1, color=factor(label))) + geom_point() + theme_classic()
	} else p21<-ggplot(blank, aes(x,y)) + theme_classic()
	if(!is.null(tmp22)){
		df22<-tmp22
		df22$label<-'old'
		df22$label[nrow(tmp22)]<-'new'
		df22<-as.data.frame(df22)
		p22<-ggplot(df22, aes(auc,pc1, color=factor(label))) + geom_point() + theme_classic()
	} else p22<-ggplot(blank, aes(x,y)) + theme_classic()
	if(!is.null(tmp23)){
		df23<-tmp23
		df23$label<-'old'
		df23$label[nrow(tmp23)]<-'new'
		df23<-as.data.frame(df23)
		p23<-ggplot(df23, aes(auc,pc1, color=factor(label))) + geom_point() + theme_classic()
	} else p23<-ggplot(blank, aes(x,y)) + theme_classic()
	if(!is.null(tmp31)){
		df31<-tmp31
		df31$label<-'old'
		df31$label[nrow(tmp31)]<-'new'
		df31<-as.data.frame(df31)
		p31<-ggplot(df31, aes(auc,pc1, color=factor(label))) + geom_point() + theme_classic()
	} else p31<-ggplot(blank, aes(x,y)) + theme_classic()
	if(!is.null(tmp32)){
		df32<-tmp32
		df32$label<-'old'
		df32$label[nrow(tmp32)]<-'new'
		df32<-as.data.frame(df32)
		p32<-ggplot(df32, aes(auc,pc1, color=factor(label))) + geom_point() + theme_classic()
	} else p32<-ggplot(blank, aes(x,y)) + theme_classic()
	if(!is.null(tmp33)){
		df33<-tmp33
		df33$label<-'old'
		df33$label[nrow(tmp33)]<-'new'
		df33<-as.data.frame(df33)
		p33<-ggplot(df33, aes(auc,pc1, color=factor(label))) + geom_point() + theme_classic()
	} else p33<-ggplot(blank, aes(x,y)) + theme_classic()
	if(!is.null(tmp41)){
		df41<-tmp41
		df41$label<-'old'
		df41$label[nrow(tmp41)]<-'new'
		df41<-as.data.frame(df41)
		p41<-ggplot(df41, aes(auc,pc1, color=factor(label))) + geom_point() + theme_classic()
	} else p41<-ggplot(blank, aes(x,y)) + theme_classic()
	if(!is.null(tmp42)){
		df42<-tmp42
		df42$label<-'old'
		df42$label[nrow(tmp42)]<-'new'
		df42<-as.data.frame(df42)
		p42<-ggplot(df42, aes(auc,pc1, color=factor(label))) + geom_point() + theme_classic()
	} else p42<-ggplot(blank, aes(x,y)) + theme_classic()
	png(filename = paste(path,"SVE_11_DEBUG_testIndex",test_index,".png",sep=""), width = 10, height = 10, units = "in", res = 200)
	plot_grid(p11,p12,p13,p21,p22,p23,p31,p32,p33,p41,p42,ncol = 3, labels = "AUTO", label_size = 16)
	dev.off()
}
MC<-c(mc11,mc12,mc13,mc21,mc22,mc23,mc31,mc32,mc33,mc41,mc42)
NBR<-c(nbr11,nbr12,nbr13,nbr21,nbr22,nbr23,nbr31,nbr32,nbr33,nbr41,nbr42)
PRED<-c(pred11,pred12,pred13,pred21,pred22,pred23,pred31,pred32,pred33,pred41,pred42)
BSC<-c(bsc11,bsc12,bsc13,bsc21,bsc22,bsc23,bsc31,bsc32,bsc33,bsc41,bsc42)
if(DEBUG) {
	print(paste('pred11:',pred11,' nbr11:',nbr11,' mc11:',mc11,' bsc11:',bsc11,sep=''))
	print(paste('pred12:',pred12,' nbr12:',nbr12,' mc12:',mc12,' bsc12:',bsc12,sep=''))
	print(paste('pred13:',pred13,' nbr13:',nbr13,' mc13:',mc13,' bsc13:',bsc13,sep=''))
	print(paste('pred21:',pred21,' nbr21:',nbr21,' mc21:',mc21,' bsc21:',bsc21,sep=''))
	print(paste('pred22:',pred22,' nbr22:',nbr22,' mc22:',mc22,' bsc22:',bsc22,sep=''))
	print(paste('pred23:',pred23,' nbr23:',nbr23,' mc23:',mc23,' bsc23:',bsc23,sep=''))
	print(paste('pred31:',pred31,' nbr31:',nbr31,' mc31:',mc31,' bsc31:',bsc31,sep=''))
	print(paste('pred32:',pred32,' nbr32:',nbr32,' mc32:',mc32,' bsc32:',bsc32,sep=''))
	print(paste('pred33:',pred33,' nbr33:',nbr33,' mc33:',mc33,' bsc33:',bsc33,sep=''))
	print(paste('pred41:',pred41,' nbr41:',nbr41,' mc41:',mc41,' bsc41:',bsc41,sep=''))
	print(paste('pred42:',pred42,' nbr42:',nbr42,' mc42:',mc42,' bsc42:',bsc42,sep=''))
}
sumNbr<-sum(NBR)
if(SELECTION==0){
	maxIndx<-which(BSC==max(BSC))[1]
	prd<-PRED[maxIndx]
} else {
	r<-2
	while(sumNbr==0 && r<=11){   ##the case where such a radius is chosen that all meanCorrelation values is 0
	radius<-RADs[r]
	r<-r+1
	if(DEBUG) print(radius)
	RAD<-radius
	nbr11<-0
	pred11<-0
	radius11<-0
	bsc11<-0 #block spearman correlation
	if(created11){
		pred11 = predict(svm11, test_normal[test_index,])
		pred11 = as.numeric(pred11)
		tmp11<-rbind(d11,c(pred11,tpc1))
		tmp11<-as.data.frame(tmp11)
		dist11<-dist(tmp11, method = "euclidean")
		dist11<-as.matrix(dist11)
		tmp111<-t(rbind(model11[,-ncol(model11)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor11<-cor(tmp111, method = c('spearman'))
		bsc11<-sum(cor11[1:nrow(cor11)-1,ncol(cor11)])/nrow(d11)
	}
	mc11<-0
	if(created11) {
		found<-which(dist11[1:nrow(dist11)-1,ncol(dist11)]<=RAD)
		neighbors11<-rownames(dist11)[found]
		nbr11<-length(found)
		if(nbr11>0){
			corIndx<-which(rownames(cor11) %in% neighbors11)   #we will look at the last column of the matrix. So matching by rownames
			mc11<-mean(cor11[corIndx,ncol(cor11)])
			if(DEBUG){
				print("svm11")
				print(neighbors11)
				print(rownames(cor11)[corIndx])
			}
		} else {
			mc11<-0
		}
	}
	nbr12<-0
	pred12<-0
	radius12<-0
	bsc12<-0 #block spearman correlation
	if(created12){
		pred12 = predict(svm12, test_normal[test_index,])
		pred12 = as.numeric(pred12)
		tmp12<-rbind(d12,c(pred12,tpc1))
		tmp12<-as.data.frame(tmp12)
		dist12<-dist(tmp12, method = "euclidean")
		dist12<-as.matrix(dist12)
		tmp121<-t(rbind(model12[,-ncol(model12)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor12<-cor(tmp121, method = c('spearman'))
		bsc12<-sum(cor12[1:nrow(cor12)-1,ncol(cor12)])/nrow(d12)
	}
	mc12<-0
	if(created12) {
		found<-which(dist12[1:nrow(dist12)-1,ncol(dist12)]<=RAD)
		neighbors12<-rownames(dist12)[found]
		nbr12<-length(found)
		if(nbr12>0){
			corIndx<-which(rownames(cor12) %in% neighbors12)   #we will look at the last column of the matrix. So matching by rownames
			mc12<-mean(cor12[corIndx,ncol(cor12)])
			if(DEBUG){
				print("svm12")
				print(neighbors12)
				print(rownames(cor12)[corIndx])
			}
		} else {
			mc12<-0
		}
	}
	nbr13<-0
	pred13<-0
	radius13<-0
	bsc13<-0 #block spearman correlation
	if(created13){
		pred13 = predict(svm13, test_normal[test_index,])
		pred13 = as.numeric(pred13)
		tmp13<-rbind(d13,c(pred13,tpc1))
		tmp13<-as.data.frame(tmp13)
		dist13<-dist(tmp13, method = "euclidean")
		dist13<-as.matrix(dist13)
		tmp131<-t(rbind(model13[,-ncol(model13)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor13<-cor(tmp131, method = c('spearman'))
		bsc13<-sum(cor13[1:nrow(cor13)-1,ncol(cor13)])/nrow(d13)
	}
	mc13<-0
	if(created13) {
		found<-which(dist13[1:nrow(dist13)-1,ncol(dist13)]<=RAD)
		neighbors13<-rownames(dist13)[found]
		nbr13<-length(found)
		if(nbr13>0){
			corIndx<-which(rownames(cor13) %in% neighbors13)   #we will look at the last column of the matrix. So matching by rownames
			mc13<-mean(cor13[corIndx,ncol(cor13)])
			if(DEBUG){
				print("svm13")
				print(neighbors13)
				print(rownames(cor13)[corIndx])
			}
		} else {
			mc13<-0
		}
	}
	nbr21<-0
	pred21<-0
	radius21<-0
	bsc21<-0 #block spearman correlation
	if(created21){
		pred21 = predict(svm21, test_normal[test_index,])
		pred21 = as.numeric(pred21)
		tmp21<-rbind(d21,c(pred21,tpc1))
		tmp21<-as.data.frame(tmp21)
		dist21<-dist(tmp21, method = "euclidean")
		dist21<-as.matrix(dist21)
		tmp211<-t(rbind(model21[,-ncol(model21)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor21<-cor(tmp211, method = c('spearman'))
		bsc21<-sum(cor21[1:nrow(cor21)-1,ncol(cor21)])/nrow(d21)
	}
	mc21<-0
	if(created21) {
		found<-which(dist21[1:nrow(dist21)-1,ncol(dist21)]<=RAD)
		neighbors21<-rownames(dist21)[found]
		nbr21<-length(found)
		if(nbr21>0){
			corIndx<-which(rownames(cor21) %in% neighbors21)   #we will look at the last column of the matrix. So matching by rownames
			mc21<-mean(cor21[corIndx,ncol(cor21)])
			if(DEBUG){
				print("svm21")
				print(neighbors21)
				print(rownames(cor21)[corIndx])
			}
		} else {
			mc21<-0
		}
	}
	nbr22<-0
	pred22<-0
	radius22<-0
	bsc22<-0 #block spearman correlation
	if(created22){
		pred22 = predict(svm22, test_normal[test_index,])
		pred22 = as.numeric(pred22)
		tmp22<-rbind(d22,c(pred22,tpc1))
		tmp22<-as.data.frame(tmp22)
		dist22<-dist(tmp22, method = "euclidean")
		dist22<-as.matrix(dist22)
		tmp221<-t(rbind(model22[,-ncol(model22)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor22<-cor(tmp221, method = c('spearman'))
		bsc22<-sum(cor22[1:nrow(cor22)-1,ncol(cor22)])/nrow(d22)
	}
	mc22<-0
	if(created22) {
		found<-which(dist22[1:nrow(dist22)-1,ncol(dist22)]<=RAD)
		neighbors22<-rownames(dist22)[found]
		nbr22<-length(found)
		if(nbr22>0){
			corIndx<-which(rownames(cor22) %in% neighbors22)   #we will look at the last column of the matrix. So matching by rownames
			mc22<-mean(cor22[corIndx,ncol(cor22)])
			if(DEBUG){
				print("svm22")
				print(neighbors22)
				print(rownames(cor22)[corIndx])
			}
		} else {
			mc22<-0
		}
	}
	nbr23<-0
	pred23<-0
	radius23<-0
	bsc23<-0 #block spearman correlation
	if(created23){
		pred23 = predict(svm23, test_normal[test_index,])
		pred23 = as.numeric(pred23)
		tmp23<-rbind(d23,c(pred23,tpc1))
		tmp23<-as.data.frame(tmp23)
		dist23<-dist(tmp23, method = "euclidean")
		dist23<-as.matrix(dist23)
		tmp231<-t(rbind(model23[,-ncol(model23)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor23<-cor(tmp231, method = c('spearman'))
		bsc23<-sum(cor23[1:nrow(cor23)-1,ncol(cor23)])/nrow(d23)
	}
	mc23<-0
	if(created23) {
		found<-which(dist23[1:nrow(dist23)-1,ncol(dist23)]<=RAD)
		neighbors23<-rownames(dist23)[found]
		nbr23<-length(found)
		if(nbr23>0){
			corIndx<-which(rownames(cor23) %in% neighbors23)   #we will look at the last column of the matrix. So matching by rownames
			mc23<-mean(cor23[corIndx,ncol(cor23)])
			if(DEBUG){
				print("svm23")
				print(neighbors23)
				print(rownames(cor23)[corIndx])
			}
		} else {
			mc23<-0
		}
	}
	nbr31<-0
	pred31<-0
	radius31<-0
	bsc31<-0 #block spearman correlation
	if(created31){
		pred31 = predict(svm31, test_normal[test_index,])
		pred31 = as.numeric(pred31)
		tmp31<-rbind(d31,c(pred31,tpc1))
		tmp31<-as.data.frame(tmp31)
		dist31<-dist(tmp31, method = "euclidean")
		dist31<-as.matrix(dist31)
		tmp311<-t(rbind(model31[,-ncol(model31)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor31<-cor(tmp311, method = c('spearman'))
		bsc31<-sum(cor31[1:nrow(cor31)-1,ncol(cor31)])/nrow(d31)
	}
	mc31<-0
	if(created31) {
		found<-which(dist31[1:nrow(dist31)-1,ncol(dist31)]<=RAD)
		neighbors31<-rownames(dist31)[found]
		nbr31<-length(found)
		if(nbr31>0){
			corIndx<-which(rownames(cor31) %in% neighbors31)   #we will look at the last column of the matrix. So matching by rownames
			mc31<-mean(cor31[corIndx,ncol(cor31)])
			if(DEBUG){
				print("svm31")
				print(neighbors31)
				print(rownames(cor31)[corIndx])
			}
		} else {
			mc31<-0
		}
	}
	nbr32<-0
	pred32<-0
	radius32<-0
	bsc32<-0 #block spearman correlation
	if(created32){
		pred32 = predict(svm32, test_normal[test_index,])
		pred32 = as.numeric(pred32)
		tmp32<-rbind(d32,c(pred32,tpc1))
		tmp32<-as.data.frame(tmp32)
		dist32<-dist(tmp32, method = "euclidean")
		dist32<-as.matrix(dist32)
		tmp321<-t(rbind(model32[,-ncol(model32)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor32<-cor(tmp321, method = c('spearman'))
		bsc32<-sum(cor32[1:nrow(cor32)-1,ncol(cor32)])/nrow(d32)
	}
	mc32<-0
	if(created32) {
		found<-which(dist32[1:nrow(dist32)-1,ncol(dist32)]<=RAD)
		neighbors32<-rownames(dist32)[found]
		nbr32<-length(found)
		if(nbr32>0){
			corIndx<-which(rownames(cor32) %in% neighbors32)   #we will look at the last column of the matrix. So matching by rownames
			mc32<-mean(cor32[corIndx,ncol(cor32)])
			if(DEBUG){
				print("svm32")
				print(neighbors32)
				print(rownames(cor32)[corIndx])
			}
		} else {
			mc32<-0
		}
	}
	nbr33<-0
	pred33<-0
	radius33<-0
	bsc33<-0 #block spearman correlation
	if(created33){
		pred33 = predict(svm33, test_normal[test_index,])
		pred33 = as.numeric(pred33)
		tmp33<-rbind(d33,c(pred33,tpc1))
		tmp33<-as.data.frame(tmp33)
		dist33<-dist(tmp33, method = "euclidean")
		dist33<-as.matrix(dist33)
		tmp331<-t(rbind(model33[,-ncol(model33)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor33<-cor(tmp331, method = c('spearman'))
		bsc33<-sum(cor33[1:nrow(cor33)-1,ncol(cor33)])/nrow(d33)
	}
	mc33<-0
	if(created33) {
		found<-which(dist33[1:nrow(dist33)-1,ncol(dist33)]<=RAD)
		neighbors33<-rownames(dist33)[found]
		nbr33<-length(found)
		if(nbr33>0){
			corIndx<-which(rownames(cor33) %in% neighbors33)   #we will look at the last column of the matrix. So matching by rownames
			mc33<-mean(cor33[corIndx,ncol(cor33)])
			if(DEBUG){
				print("svm33")
				print(neighbors33)
				print(rownames(cor33)[corIndx])
			}
		} else {
			mc33<-0
		}
	}
	nbr41<-0
	pred41<-0
	radius41<-0
	bsc41<-0 #block spearman correlation
	if(created41){
		pred41 = predict(svm41, test_normal[test_index,])
		pred41 = as.numeric(pred41)
		tmp41<-rbind(d41,c(pred41,tpc1))
		tmp41<-as.data.frame(tmp41)
		dist41<-dist(tmp41, method = "euclidean")
		dist41<-as.matrix(dist41)
		tmp411<-t(rbind(model41[,-ncol(model41)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor41<-cor(tmp411, method = c('spearman'))
		bsc41<-sum(cor41[1:nrow(cor41)-1,ncol(cor41)])/nrow(d41)
	}
	mc41<-0
	if(created41) {
		found<-which(dist41[1:nrow(dist41)-1,ncol(dist41)]<=RAD)
		neighbors41<-rownames(dist41)[found]
		nbr41<-length(found)
		if(nbr41>0){
			corIndx<-which(rownames(cor41) %in% neighbors41)   #we will look at the last column of the matrix. So matching by rownames
			mc41<-mean(cor41[corIndx,ncol(cor41)])
			if(DEBUG){
				print("svm41")
				print(neighbors41)
				print(rownames(cor41)[corIndx])
			}
		} else {
			mc41<-0
		}
	}
	nbr42<-0
	pred42<-0
	radius42<-0
	bsc42<-0 #block spearman correlation
	if(created42){
		pred42 = predict(svm42, test_normal[test_index,])
		pred42 = as.numeric(pred42)
		tmp42<-rbind(d42,c(pred42,tpc1))
		tmp42<-as.data.frame(tmp42)
		dist42<-dist(tmp42, method = "euclidean")
		dist42<-as.matrix(dist42)
		tmp421<-t(rbind(model42[,-ncol(model42)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor42<-cor(tmp421, method = c('spearman'))
		bsc42<-sum(cor42[1:nrow(cor42)-1,ncol(cor42)])/nrow(d42)
	}
	mc42<-0
	if(created42) {
		found<-which(dist42[1:nrow(dist42)-1,ncol(dist42)]<=RAD)
		neighbors42<-rownames(dist42)[found]
		nbr42<-length(found)
		if(nbr42>0){
			corIndx<-which(rownames(cor42) %in% neighbors42)   #we will look at the last column of the matrix. So matching by rownames
			mc42<-mean(cor42[corIndx,ncol(cor42)])
			if(DEBUG){
				print("svm42")
				print(neighbors42)
				print(rownames(cor42)[corIndx])
			}
		} else {
			mc42<-0
		}
	}
	MC<-c(mc11,mc12,mc13,mc21,mc22,mc23,mc31,mc32,mc33,mc41,mc42)
	NBR<-c(nbr11,nbr12,nbr13,nbr21,nbr22,nbr23,nbr31,nbr32,nbr33,nbr41,nbr42)
	PRED<-c(pred11,pred12,pred13,pred21,pred22,pred23,pred31,pred32,pred33,pred41,pred42)
	sumNbr<-sum(NBR)
	if(DEBUG) {
		print(paste('pred11:',pred11,' nbr11:',nbr11,' mc11:',mc11,sep=''))
		print(paste('pred12:',pred12,' nbr12:',nbr12,' mc12:',mc12,sep=''))
		print(paste('pred13:',pred13,' nbr13:',nbr13,' mc13:',mc13,sep=''))
		print(paste('pred21:',pred21,' nbr21:',nbr21,' mc21:',mc21,sep=''))
		print(paste('pred22:',pred22,' nbr22:',nbr22,' mc22:',mc22,sep=''))
		print(paste('pred23:',pred23,' nbr23:',nbr23,' mc23:',mc23,sep=''))
		print(paste('pred31:',pred31,' nbr31:',nbr31,' mc31:',mc31,sep=''))
		print(paste('pred32:',pred32,' nbr32:',nbr32,' mc32:',mc32,sep=''))
		print(paste('pred33:',pred33,' nbr33:',nbr33,' mc33:',mc33,sep=''))
		print(paste('pred41:',pred41,' nbr41:',nbr41,' mc41:',mc41,sep=''))
		print(paste('pred42:',pred42,' nbr42:',nbr42,' mc42:',mc42,sep=''))
	}
	} ##while  #going through the RADs vector one by one
	#still no neighbors
	if(sumNbr==0){
	RAD<-500
	nbr11<-0
	pred11<-0
	radius11<-0
	bsc11<-0 #block spearman correlation
	if(created11){
		pred11 = predict(svm11, test_normal[test_index,])
		pred11 = as.numeric(pred11)
		tmp11<-rbind(d11,c(pred11,tpc1))
		tmp11<-as.data.frame(tmp11)
		dist11<-dist(tmp11, method = "euclidean")
		dist11<-as.matrix(dist11)
		tmp111<-t(rbind(model11[,-ncol(model11)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor11<-cor(tmp111, method = c('spearman'))
		bsc11<-sum(cor11[1:nrow(cor11)-1,ncol(cor11)])/nrow(d11)
	}
	mc11<-0
	if(created11) {
		found<-which(dist11[1:nrow(dist11)-1,ncol(dist11)]<=RAD)
		neighbors11<-rownames(dist11)[found]
		nbr11<-length(found)
		if(nbr11>0){
			corIndx<-which(rownames(cor11) %in% neighbors11)   #we will look at the last column of the matrix. So matching by rownames
			mc11<-mean(cor11[corIndx,ncol(cor11)])
			if(DEBUG){
				print("svm11")
				print(neighbors11)
				print(rownames(cor11)[corIndx])
			}
		} else {
			mc11<-0
		}
	}
	nbr12<-0
	pred12<-0
	radius12<-0
	bsc12<-0 #block spearman correlation
	if(created12){
		pred12 = predict(svm12, test_normal[test_index,])
		pred12 = as.numeric(pred12)
		tmp12<-rbind(d12,c(pred12,tpc1))
		tmp12<-as.data.frame(tmp12)
		dist12<-dist(tmp12, method = "euclidean")
		dist12<-as.matrix(dist12)
		tmp121<-t(rbind(model12[,-ncol(model12)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor12<-cor(tmp121, method = c('spearman'))
		bsc12<-sum(cor12[1:nrow(cor12)-1,ncol(cor12)])/nrow(d12)
	}
	mc12<-0
	if(created12) {
		found<-which(dist12[1:nrow(dist12)-1,ncol(dist12)]<=RAD)
		neighbors12<-rownames(dist12)[found]
		nbr12<-length(found)
		if(nbr12>0){
			corIndx<-which(rownames(cor12) %in% neighbors12)   #we will look at the last column of the matrix. So matching by rownames
			mc12<-mean(cor12[corIndx,ncol(cor12)])
			if(DEBUG){
				print("svm12")
				print(neighbors12)
				print(rownames(cor12)[corIndx])
			}
		} else {
			mc12<-0
		}
	}
	nbr13<-0
	pred13<-0
	radius13<-0
	bsc13<-0 #block spearman correlation
	if(created13){
		pred13 = predict(svm13, test_normal[test_index,])
		pred13 = as.numeric(pred13)
		tmp13<-rbind(d13,c(pred13,tpc1))
		tmp13<-as.data.frame(tmp13)
		dist13<-dist(tmp13, method = "euclidean")
		dist13<-as.matrix(dist13)
		tmp131<-t(rbind(model13[,-ncol(model13)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor13<-cor(tmp131, method = c('spearman'))
		bsc13<-sum(cor13[1:nrow(cor13)-1,ncol(cor13)])/nrow(d13)
	}
	mc13<-0
	if(created13) {
		found<-which(dist13[1:nrow(dist13)-1,ncol(dist13)]<=RAD)
		neighbors13<-rownames(dist13)[found]
		nbr13<-length(found)
		if(nbr13>0){
			corIndx<-which(rownames(cor13) %in% neighbors13)   #we will look at the last column of the matrix. So matching by rownames
			mc13<-mean(cor13[corIndx,ncol(cor13)])
			if(DEBUG){
				print("svm13")
				print(neighbors13)
				print(rownames(cor13)[corIndx])
			}
		} else {
			mc13<-0
		}
	}
	nbr21<-0
	pred21<-0
	radius21<-0
	bsc21<-0 #block spearman correlation
	if(created21){
		pred21 = predict(svm21, test_normal[test_index,])
		pred21 = as.numeric(pred21)
		tmp21<-rbind(d21,c(pred21,tpc1))
		tmp21<-as.data.frame(tmp21)
		dist21<-dist(tmp21, method = "euclidean")
		dist21<-as.matrix(dist21)
		tmp211<-t(rbind(model21[,-ncol(model21)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor21<-cor(tmp211, method = c('spearman'))
		bsc21<-sum(cor21[1:nrow(cor21)-1,ncol(cor21)])/nrow(d21)
	}
	mc21<-0
	if(created21) {
		found<-which(dist21[1:nrow(dist21)-1,ncol(dist21)]<=RAD)
		neighbors21<-rownames(dist21)[found]
		nbr21<-length(found)
		if(nbr21>0){
			corIndx<-which(rownames(cor21) %in% neighbors21)   #we will look at the last column of the matrix. So matching by rownames
			mc21<-mean(cor21[corIndx,ncol(cor21)])
			if(DEBUG){
				print("svm21")
				print(neighbors21)
				print(rownames(cor21)[corIndx])
			}
		} else {
			mc21<-0
		}
	}
	nbr22<-0
	pred22<-0
	radius22<-0
	bsc22<-0 #block spearman correlation
	if(created22){
		pred22 = predict(svm22, test_normal[test_index,])
		pred22 = as.numeric(pred22)
		tmp22<-rbind(d22,c(pred22,tpc1))
		tmp22<-as.data.frame(tmp22)
		dist22<-dist(tmp22, method = "euclidean")
		dist22<-as.matrix(dist22)
		tmp221<-t(rbind(model22[,-ncol(model22)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor22<-cor(tmp221, method = c('spearman'))
		bsc22<-sum(cor22[1:nrow(cor22)-1,ncol(cor22)])/nrow(d22)
	}
	mc22<-0
	if(created22) {
		found<-which(dist22[1:nrow(dist22)-1,ncol(dist22)]<=RAD)
		neighbors22<-rownames(dist22)[found]
		nbr22<-length(found)
		if(nbr22>0){
			corIndx<-which(rownames(cor22) %in% neighbors22)   #we will look at the last column of the matrix. So matching by rownames
			mc22<-mean(cor22[corIndx,ncol(cor22)])
			if(DEBUG){
				print("svm22")
				print(neighbors22)
				print(rownames(cor22)[corIndx])
			}
		} else {
			mc22<-0
		}
	}
	nbr23<-0
	pred23<-0
	radius23<-0
	bsc23<-0 #block spearman correlation
	if(created23){
		pred23 = predict(svm23, test_normal[test_index,])
		pred23 = as.numeric(pred23)
		tmp23<-rbind(d23,c(pred23,tpc1))
		tmp23<-as.data.frame(tmp23)
		dist23<-dist(tmp23, method = "euclidean")
		dist23<-as.matrix(dist23)
		tmp231<-t(rbind(model23[,-ncol(model23)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor23<-cor(tmp231, method = c('spearman'))
		bsc23<-sum(cor23[1:nrow(cor23)-1,ncol(cor23)])/nrow(d23)
	}
	mc23<-0
	if(created23) {
		found<-which(dist23[1:nrow(dist23)-1,ncol(dist23)]<=RAD)
		neighbors23<-rownames(dist23)[found]
		nbr23<-length(found)
		if(nbr23>0){
			corIndx<-which(rownames(cor23) %in% neighbors23)   #we will look at the last column of the matrix. So matching by rownames
			mc23<-mean(cor23[corIndx,ncol(cor23)])
			if(DEBUG){
				print("svm23")
				print(neighbors23)
				print(rownames(cor23)[corIndx])
			}
		} else {
			mc23<-0
		}
	}
	nbr31<-0
	pred31<-0
	radius31<-0
	bsc31<-0 #block spearman correlation
	if(created31){
		pred31 = predict(svm31, test_normal[test_index,])
		pred31 = as.numeric(pred31)
		tmp31<-rbind(d31,c(pred31,tpc1))
		tmp31<-as.data.frame(tmp31)
		dist31<-dist(tmp31, method = "euclidean")
		dist31<-as.matrix(dist31)
		tmp311<-t(rbind(model31[,-ncol(model31)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor31<-cor(tmp311, method = c('spearman'))
		bsc31<-sum(cor31[1:nrow(cor31)-1,ncol(cor31)])/nrow(d31)
	}
	mc31<-0
	if(created31) {
		found<-which(dist31[1:nrow(dist31)-1,ncol(dist31)]<=RAD)
		neighbors31<-rownames(dist31)[found]
		nbr31<-length(found)
		if(nbr31>0){
			corIndx<-which(rownames(cor31) %in% neighbors31)   #we will look at the last column of the matrix. So matching by rownames
			mc31<-mean(cor31[corIndx,ncol(cor31)])
			if(DEBUG){
				print("svm31")
				print(neighbors31)
				print(rownames(cor31)[corIndx])
			}
		} else {
			mc31<-0
		}
	}
	nbr32<-0
	pred32<-0
	radius32<-0
	bsc32<-0 #block spearman correlation
	if(created32){
		pred32 = predict(svm32, test_normal[test_index,])
		pred32 = as.numeric(pred32)
		tmp32<-rbind(d32,c(pred32,tpc1))
		tmp32<-as.data.frame(tmp32)
		dist32<-dist(tmp32, method = "euclidean")
		dist32<-as.matrix(dist32)
		tmp321<-t(rbind(model32[,-ncol(model32)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor32<-cor(tmp321, method = c('spearman'))
		bsc32<-sum(cor32[1:nrow(cor32)-1,ncol(cor32)])/nrow(d32)
	}
	mc32<-0
	if(created32) {
		found<-which(dist32[1:nrow(dist32)-1,ncol(dist32)]<=RAD)
		neighbors32<-rownames(dist32)[found]
		nbr32<-length(found)
		if(nbr32>0){
			corIndx<-which(rownames(cor32) %in% neighbors32)   #we will look at the last column of the matrix. So matching by rownames
			mc32<-mean(cor32[corIndx,ncol(cor32)])
			if(DEBUG){
				print("svm32")
				print(neighbors32)
				print(rownames(cor32)[corIndx])
			}
		} else {
			mc32<-0
		}
	}
	nbr33<-0
	pred33<-0
	radius33<-0
	bsc33<-0 #block spearman correlation
	if(created33){
		pred33 = predict(svm33, test_normal[test_index,])
		pred33 = as.numeric(pred33)
		tmp33<-rbind(d33,c(pred33,tpc1))
		tmp33<-as.data.frame(tmp33)
		dist33<-dist(tmp33, method = "euclidean")
		dist33<-as.matrix(dist33)
		tmp331<-t(rbind(model33[,-ncol(model33)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor33<-cor(tmp331, method = c('spearman'))
		bsc33<-sum(cor33[1:nrow(cor33)-1,ncol(cor33)])/nrow(d33)
	}
	mc33<-0
	if(created33) {
		found<-which(dist33[1:nrow(dist33)-1,ncol(dist33)]<=RAD)
		neighbors33<-rownames(dist33)[found]
		nbr33<-length(found)
		if(nbr33>0){
			corIndx<-which(rownames(cor33) %in% neighbors33)   #we will look at the last column of the matrix. So matching by rownames
			mc33<-mean(cor33[corIndx,ncol(cor33)])
			if(DEBUG){
				print("svm33")
				print(neighbors33)
				print(rownames(cor33)[corIndx])
			}
		} else {
			mc33<-0
		}
	}
	nbr41<-0
	pred41<-0
	radius41<-0
	bsc41<-0 #block spearman correlation
	if(created41){
		pred41 = predict(svm41, test_normal[test_index,])
		pred41 = as.numeric(pred41)
		tmp41<-rbind(d41,c(pred41,tpc1))
		tmp41<-as.data.frame(tmp41)
		dist41<-dist(tmp41, method = "euclidean")
		dist41<-as.matrix(dist41)
		tmp411<-t(rbind(model41[,-ncol(model41)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor41<-cor(tmp411, method = c('spearman'))
		bsc41<-sum(cor41[1:nrow(cor41)-1,ncol(cor41)])/nrow(d41)
	}
	mc41<-0
	if(created41) {
		found<-which(dist41[1:nrow(dist41)-1,ncol(dist41)]<=RAD)
		neighbors41<-rownames(dist41)[found]
		nbr41<-length(found)
		if(nbr41>0){
			corIndx<-which(rownames(cor41) %in% neighbors41)   #we will look at the last column of the matrix. So matching by rownames
			mc41<-mean(cor41[corIndx,ncol(cor41)])
			if(DEBUG){
				print("svm41")
				print(neighbors41)
				print(rownames(cor41)[corIndx])
			}
		} else {
			mc41<-0
		}
	}
	nbr42<-0
	pred42<-0
	radius42<-0
	bsc42<-0 #block spearman correlation
	if(created42){
		pred42 = predict(svm42, test_normal[test_index,])
		pred42 = as.numeric(pred42)
		tmp42<-rbind(d42,c(pred42,tpc1))
		tmp42<-as.data.frame(tmp42)
		dist42<-dist(tmp42, method = "euclidean")
		dist42<-as.matrix(dist42)
		tmp421<-t(rbind(model42[,-ncol(model42)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor42<-cor(tmp421, method = c('spearman'))
		bsc42<-sum(cor42[1:nrow(cor42)-1,ncol(cor42)])/nrow(d42)
	}
	mc42<-0
	if(created42) {
		found<-which(dist42[1:nrow(dist42)-1,ncol(dist42)]<=RAD)
		neighbors42<-rownames(dist42)[found]
		nbr42<-length(found)
		if(nbr42>0){
			corIndx<-which(rownames(cor42) %in% neighbors42)   #we will look at the last column of the matrix. So matching by rownames
			mc42<-mean(cor42[corIndx,ncol(cor42)])
			if(DEBUG){
				print("svm42")
				print(neighbors42)
				print(rownames(cor42)[corIndx])
			}
		} else {
			mc42<-0
		}
	}
	MC<-c(mc11,mc12,mc13,mc21,mc22,mc23,mc31,mc32,mc33,mc41,mc42)
	NBR<-c(nbr11,nbr12,nbr13,nbr21,nbr22,nbr23,nbr31,nbr32,nbr33,nbr41,nbr42)
	PRED<-c(pred11,pred12,pred13,pred21,pred22,pred23,pred31,pred32,pred33,pred41,pred42)
	sumNbr<-sum(NBR)
	if(DEBUG) {
		print(paste('pred11:',pred11,' nbr11:',nbr11,' mc11:',mc11,sep=''))
		print(paste('pred12:',pred12,' nbr12:',nbr12,' mc12:',mc12,sep=''))
		print(paste('pred13:',pred13,' nbr13:',nbr13,' mc13:',mc13,sep=''))
		print(paste('pred21:',pred21,' nbr21:',nbr21,' mc21:',mc21,sep=''))
		print(paste('pred22:',pred22,' nbr22:',nbr22,' mc22:',mc22,sep=''))
		print(paste('pred23:',pred23,' nbr23:',nbr23,' mc23:',mc23,sep=''))
		print(paste('pred31:',pred31,' nbr31:',nbr31,' mc31:',mc31,sep=''))
		print(paste('pred32:',pred32,' nbr32:',nbr32,' mc32:',mc32,sep=''))
		print(paste('pred33:',pred33,' nbr33:',nbr33,' mc33:',mc33,sep=''))
		print(paste('pred41:',pred41,' nbr41:',nbr41,' mc41:',mc41,sep=''))
		print(paste('pred42:',pred42,' nbr42:',nbr42,' mc42:',mc42,sep=''))
	}
	}#using radius = 500
} ##SELECTION!=0
if(SELECTION==1){
	maxIndx<-which(MC==max(MC))[1]
	prd<-PRED[maxIndx]
} else if(SELECTION==2){
	wMC<-MC/sum(MC)
	prd<-sum(wMC*PRED)
} else if(SELECTION==3){
	maxIndx<-which(NBR==max(NBR))[1]
	prd<-PRED[maxIndx]
} else if(SELECTION==4){
	wNb<-NBR/sum(NBR)
	prd<-sum(wNb*PRED)
}
if(DEBUG) print(paste("SELECTION:",SELECTION," real: ",test_normal[test_index,ncol(test_normal)]," prd: ",prd, sep = ''))
prd
} #end SVMEnsemble_11_howtopredict()




SVMEnsemble_11<-function(blocks,percTesting,SELECTION,fold,N,CV,DEBUG,ALLDATA,DIST,y,yName,PATH){

if(DEBUG){
	print(drug_index)
	print(drug_names[drug_index])
}

cv_sse<-0

TUNELENGTH<-10 

CL11<-blocks[[1]]
CL12<-blocks[[2]]
CL13<-blocks[[3]]
CL21<-blocks[[4]]
CL22<-blocks[[5]]
CL23<-blocks[[6]]
CL31<-blocks[[7]]
CL32<-blocks[[8]]
CL33<-blocks[[9]]
CL41<-blocks[[10]]
CL42<-blocks[[11]]

#model based on CL11
m11<-FALSE
if(length(CL11)>0){
	m11<-TRUE
	d11<-DIST[(which(rownames(DIST) %in% CL11)),]
	d11<-as.data.frame(d11)
	tmp<-which(rownames(ALLDATA) %in% CL11)
	model11<-ALLDATA[tmp,]
	model11<-as.data.frame(model11)
}
#model based on CL12
m12<-FALSE
if(length(CL12)>0){
	m12<-TRUE
	d12<-DIST[(which(rownames(DIST) %in% CL12)),]
	d12<-as.data.frame(d12)
	tmp<-which(rownames(ALLDATA) %in% CL12)
	model12<-ALLDATA[tmp,]
	model12<-as.data.frame(model12)
}
#model based on CL13
m13<-FALSE
if(length(CL13)>0){
	m13<-TRUE
	d13<-DIST[(which(rownames(DIST) %in% CL13)),]
	d13<-as.data.frame(d13)
	tmp<-which(rownames(ALLDATA) %in% CL13)
	model13<-ALLDATA[tmp,]
	model13<-as.data.frame(model13)
}
#model based on CL21
m21<-FALSE
if(length(CL21)>0){
	m21<-TRUE
	d21<-DIST[(which(rownames(DIST) %in% CL21)),]
	d21<-as.data.frame(d21)
	tmp<-which(rownames(ALLDATA) %in% CL21)
	model21<-ALLDATA[tmp,]
	model21<-as.data.frame(model21)
}
#model based on CL22
m22<-FALSE
if(length(CL22)>0){
	m22<-TRUE
	d22<-DIST[(which(rownames(DIST) %in% CL22)),]
	d22<-as.data.frame(d22)
	tmp<-which(rownames(ALLDATA) %in% CL22)
	model22<-ALLDATA[tmp,]
	model22<-as.data.frame(model22)
}
#model based on CL23
m23<-FALSE
if(length(CL23)>0){
	m23<-TRUE
	d23<-DIST[(which(rownames(DIST) %in% CL23)),]
	d23<-as.data.frame(d23)
	tmp<-which(rownames(ALLDATA) %in% CL23)
	model23<-ALLDATA[tmp,]
	model23<-as.data.frame(model23)
}
#model based on CL31
m31<-FALSE
if(length(CL31)>0){
	m31<-TRUE
	d31<-DIST[(which(rownames(DIST) %in% CL31)),]
	d31<-as.data.frame(d31)
	tmp<-which(rownames(ALLDATA) %in% CL31)
	model31<-ALLDATA[tmp,]
	model31<-as.data.frame(model31)
}
#model based on CL32
m32<-FALSE
if(length(CL32)>0){
	m32<-TRUE
	d32<-DIST[(which(rownames(DIST) %in% CL32)),]
	d32<-as.data.frame(d32)
	tmp<-which(rownames(ALLDATA) %in% CL32)
	model32<-ALLDATA[tmp,]
	model32<-as.data.frame(model32)
}
#model based on CL33
m33<-FALSE
if(length(CL33)>0){
	m33<-TRUE
	d33<-DIST[(which(rownames(DIST) %in% CL33)),]
	d33<-as.data.frame(d33)
	tmp<-which(rownames(ALLDATA) %in% CL33)
	model33<-ALLDATA[tmp,]
	model33<-as.data.frame(model33)
}
#model based on CL41
m41<-FALSE
if(length(CL41)>0){
	m41<-TRUE
	d41<-DIST[(which(rownames(DIST) %in% CL41)),]
	d41<-as.data.frame(d41)
	tmp<-which(rownames(ALLDATA) %in% CL41)
	model41<-ALLDATA[tmp,]
	model41<-as.data.frame(model41)
}
#model based on CL42
m42<-FALSE
if(length(CL42)>0){
	m42<-TRUE
	d42<-DIST[(which(rownames(DIST) %in% CL42)),]
	d42<-as.data.frame(d42)
	tmp<-which(rownames(ALLDATA) %in% CL42)
	model42<-ALLDATA[tmp,]
	model42<-as.data.frame(model42)
}

MINSAMPLES<-10

if(DEBUG) print(drug_names[drug_index])
formula = paste(drug_names[drug_index], '~.', sep = '')

bSigma11=-1
bC11=-1
bSigma12=-1
bC12=-1
bSigma13=-1
bC13=-1
bSigma21=-1
bC21=-1
bSigma22=-1
bC22=-1
bSigma23=-1
bC23=-1
bSigma31=-1
bC31=-1
bSigma32=-1
bC32=-1
bSigma33=-1
bC33=-1
bSigma41=-1
bC41=-1
bSigma42=-1
bC42=-1

bestMSE=999999

edgeIndices<-getFoldIndices(length(yName),fold)

Train_r2_svmB<-c()
Train_mse_svmB<-c()
Test_r2_svmB<-c()
Test_mse_svmB<-c()
firstCol<-c()
Avg_testtrain<-c()

if(CV==0) repetitions = fold else repetitions = N

firstCol<-c(1:repetitions)

f<-1
for(f in 1:repetitions){

if(DEBUG) print(paste('fold/iteration: ',f,sep = '')) 

if(CV==0){  #normal cross-validation
	testNames<-yName[edgeIndices[[f]]]
	trainNames<-yName[-edgeIndices[[f]]]
} else { # repeated crossvalidation
	test<-sample(1:length(yName), percTesting*length(yName))
	testNames<-yName[test]
	trainNames<-yName[-test]
}

testIndx<-which(rownames(ALLDATA) %in% testNames)
trainIndx<-which(rownames(ALLDATA) %in% trainNames)
test_normal<-ALLDATA[testIndx,]
test_normal<-as.data.frame(test_normal)
train_normal<-ALLDATA[trainIndx,]
train_normal<-as.data.frame(train_normal)

ix11=-1
if(m11) {
	ix11<-which(rownames(model11) %in% trainNames)
	if(length(ix11)==0) ix11=-1
}
sigma11=-1
C11=-1

ix12=-1
if(m12) {
	ix12<-which(rownames(model12) %in% trainNames)
	if(length(ix12)==0) ix12=-1
}
sigma12=-1
C12=-1

ix13=-1
if(m13) {
	ix13<-which(rownames(model13) %in% trainNames)
	if(length(ix13)==0) ix13=-1
}
sigma13=-1
C13=-1

ix21=-1
if(m21) {
	ix21<-which(rownames(model21) %in% trainNames)
	if(length(ix21)==0) ix21=-1
}
sigma21=-1
C21=-1

ix22=-1
if(m22) {
	ix22<-which(rownames(model22) %in% trainNames)
	if(length(ix22)==0) ix22=-1
}
sigma22=-1
C22=-1

ix23=-1
if(m23) {
	ix23<-which(rownames(model23) %in% trainNames)
	if(length(ix23)==0) ix23=-1
}
sigma23=-1
C23=-1

ix31=-1
if(m31) {
	ix31<-which(rownames(model31) %in% trainNames)
	if(length(ix31)==0) ix31=-1
}
sigma31=-1
C31=-1

ix32=-1
if(m32) {
	ix32<-which(rownames(model32) %in% trainNames)
	if(length(ix32)==0) ix32=-1
}
sigma32=-1
C32=-1

ix33=-1
if(m33) {
	ix33<-which(rownames(model33) %in% trainNames)
	if(length(ix33)==0) ix33=-1
}
sigma33=-1
C33=-1

ix41=-1
if(m41) {
	ix41<-which(rownames(model41) %in% trainNames)
	if(length(ix41)==0) ix41=-1
}
sigma41=-1
C41=-1

ix42=-1
if(m42) {
	ix42<-which(rownames(model42) %in% trainNames)
	if(length(ix42)==0) ix42=-1
}
sigma42=-1
C42=-1


created11<-FALSE #model created or not
if(m11){
	if(length(ix11)>MINSAMPLES){
		created11<-TRUE
		train11 = model11[ix11, ]
		svm11 <- train(as.formula(formula), data = train11, method = "svmRadial", tuneLength = 10)
		sigma11<-svm11$bestTune$sigma
		C11<-svm11$bestTune$C
	}
}
created12<-FALSE #model created or not
if(m12){
	if(length(ix12)>MINSAMPLES){
		created12<-TRUE
		train12 = model12[ix12, ]
		svm12 <- train(as.formula(formula), data = train12, method = "svmRadial", tuneLength = 10)
		sigma12<-svm12$bestTune$sigma
		C12<-svm12$bestTune$C
	}
}
created13<-FALSE #model created or not
if(m13){
	if(length(ix13)>MINSAMPLES){
		created13<-TRUE
		train13 = model13[ix13, ]
		svm13 <- train(as.formula(formula), data = train13, method = "svmRadial", tuneLength = 10)
		sigma13<-svm13$bestTune$sigma
		C13<-svm13$bestTune$C
	}
}
created21<-FALSE #model created or not
if(m21){
	if(length(ix21)>MINSAMPLES){
		created21<-TRUE
		train21 = model21[ix21, ]
		svm21 <- train(as.formula(formula), data = train21, method = "svmRadial", tuneLength = 10)
		sigma21<-svm21$bestTune$sigma
		C21<-svm21$bestTune$C
	}
}
created22<-FALSE #model created or not
if(m22){
	if(length(ix22)>MINSAMPLES){
		created22<-TRUE
		train22 = model22[ix22, ]
		svm22 <- train(as.formula(formula), data = train22, method = "svmRadial", tuneLength = 10)
		sigma22<-svm22$bestTune$sigma
		C22<-svm22$bestTune$C
	}
}
created23<-FALSE #model created or not
if(m23){
	if(length(ix23)>MINSAMPLES){
		created23<-TRUE
		train23 = model23[ix23, ]
		svm23 <- train(as.formula(formula), data = train23, method = "svmRadial", tuneLength = 10)
		sigma23<-svm23$bestTune$sigma
		C23<-svm23$bestTune$C
	}
}
created31<-FALSE #model created or not
if(m31){
	if(length(ix31)>MINSAMPLES){
		created31<-TRUE
		train31 = model31[ix31, ]
		svm31 <- train(as.formula(formula), data = train31, method = "svmRadial", tuneLength = 10)
		sigma31<-svm31$bestTune$sigma
		C31<-svm31$bestTune$C
	}
}
created32<-FALSE #model created or not
if(m32){
	if(length(ix32)>MINSAMPLES){
		created32<-TRUE
		train32 = model32[ix32, ]
		svm32 <- train(as.formula(formula), data = train32, method = "svmRadial", tuneLength = 10)
		sigma32<-svm32$bestTune$sigma
		C32<-svm32$bestTune$C
	}
}
created33<-FALSE #model created or not
if(m33){
	if(length(ix33)>MINSAMPLES){
		created33<-TRUE
		train33 = model33[ix33, ]
		svm33 <- train(as.formula(formula), data = train33, method = "svmRadial", tuneLength = 10)
		sigma33<-svm33$bestTune$sigma
		C33<-svm33$bestTune$C
	}
}
created41<-FALSE #model created or not
if(m41){
	if(length(ix41)>MINSAMPLES){
		created41<-TRUE
		train41 = model41[ix41, ]
		svm41 <- train(as.formula(formula), data = train41, method = "svmRadial", tuneLength = 10)
		sigma41<-svm41$bestTune$sigma
		C41<-svm41$bestTune$C
	}
}
created42<-FALSE #model created or not
if(m42){
	if(length(ix42)>MINSAMPLES){
		created42<-TRUE
		train42 = model42[ix42, ]
		svm42 <- train(as.formula(formula), data = train42, method = "svmRadial", tuneLength = 10)
		sigma42<-svm42$bestTune$sigma
		C42<-svm42$bestTune$C
	}
}

###########################train_normal######################

L<-nrow(train_normal)

#vector containing the final prediction values
predTrain<-c()

if(DEBUG) {
	L=5
	print('TRAINING DATA')
}
train_index<-1

for(train_index in 1:L){

	predTrain<-c(predTrain,SVMEnsemble_11_howtopredict(SELECTION,train_normal,train_index,y,yName,d11,created11,model11,svm11,d12,created12,model12,svm12,d13,created13,model13,svm13,d21,created21,model21,svm21,d22,created22,model22,svm22,d23,created23,model23,svm23,d31,created31,model31,svm31,d32,created32,model32,svm32,d33,created33,model33,svm33,d41,created41,model41,svm41,d42,created42,model42,svm42))

} #train_index

predTrain<-as.numeric(predTrain)

mse_trtmp<-MSE(train_normal[1:L,ncol(train_normal)],predTrain)

sse_trtmp<-sum((train_normal[1:L,ncol(train_normal)]-predTrain)^2)

Train_mse_svmB = c(Train_mse_svmB,mse_trtmp)

###########################train_normal######################

###########################test_normal######################

L<-nrow(test_normal)

#vector containing the final prediction values
predTest<-c()

if(DEBUG) {
	L=5
	print('TESTING DATA')
}
test_index<-1

for(test_index in 1:L){

	predTest<-c(predTest,SVMEnsemble_11_howtopredict(SELECTION,test_normal,test_index,y,yName,d11,created11,model11,svm11,d12,created12,model12,svm12,d13,created13,model13,svm13,d21,created21,model21,svm21,d22,created22,model22,svm22,d23,created23,model23,svm23,d31,created31,model31,svm31,d32,created32,model32,svm32,d33,created33,model33,svm33,d41,created41,model41,svm41,d42,created42,model42,svm42))

} #test_index

predTest<-as.numeric(predTest)

mse_tmp<-MSE(test_normal[1:L,ncol(test_normal)],predTest)

sse_tmp<-sum((test_normal[1:L,ncol(test_normal)]-predTest)^2)

cv_sse<-cv_sse + sum((test_normal[1:L,ncol(test_normal)]-predTest)^2)

Test_mse_svmB = c(Test_mse_svmB,mse_tmp)

###########################test_normal######################

Avg_testtrain<-c(Avg_testtrain,mean(c(mse_trtmp,mse_tmp)))

if(mean(c(mse_trtmp,mse_tmp))<bestMSE){
	bestMSE=mean(c(mse_trtmp,mse_tmp))

	bSigma11=sigma11
	bC11=C11
	bSigma12=sigma12
	bC12=C12
	bSigma13=sigma13
	bC13=C13
	bSigma21=sigma21
	bC21=C21
	bSigma22=sigma22
	bC22=C22
	bSigma23=sigma23
	bC23=C23
	bSigma31=sigma31
	bC31=C31
	bSigma32=sigma32
	bC32=C32
	bSigma33=sigma33
	bC33=C33
	bSigma41=sigma41
	bC41=C41
	bSigma42=sigma42
	bC42=C42
	trNames<-trainNames
	teNames<-testNames
}

print(paste('CV Fold/Iteration-',f,' Train_mse: ',mse_trtmp,' Test_mse: ',mse_tmp,' Avg_Train_Test_mse: ',mean(c(mse_trtmp,mse_tmp)),sep = ''))

} # cross-validation

tbw<-data.frame(firstCol,Train_mse_svmB,Test_mse_svmB,Avg_testtrain)
colnames(tbw)<-c('Iteration/Fold','Train_MSE','Test_MSE','Avg_Train_Test_MSE')
write.csv(tbw,paste(PATH,'SVMEnsemble_11_',drug_names[drug_index],'.csv',sep = ''), row.names = F, quote = F)

meanSqError<-mean(Avg_testtrain)

print(paste('Fitness','Avg_MSE',sep = ' '))
print(c(1/meanSqError,meanSqError))

print(paste('k=11_CV_RMSE',sqrt(cv_sse/nrow(ALLDATA)),sep=' '))

list(c(meanSqError,bestMSE),c(bSigma11,bC11,bSigma12,bC12,bSigma13,bC13,bSigma21,bC21,bSigma22,bC22,bSigma23,bC23,bSigma31,bC31,bSigma32,bC32,bSigma33,bC33,bSigma41,bC41,bSigma42,bC42),trNames,teNames)

} #end SVMEnsemble_11()



SVMEnsemble_11_Replicate<-function(params,blocks,SELECTION,DEBUG,ALLDATA,DIST,y,yName){

if(DEBUG){
	print(drug_index)
	print(drug_names[drug_index])
}

TUNELENGTH<-10 

CL11<-blocks[[1]]
CL12<-blocks[[2]]
CL13<-blocks[[3]]
CL21<-blocks[[4]]
CL22<-blocks[[5]]
CL23<-blocks[[6]]
CL31<-blocks[[7]]
CL32<-blocks[[8]]
CL33<-blocks[[9]]
CL41<-blocks[[10]]
CL42<-blocks[[11]]

tuningParameters<-params[[2]]

trainNames<-params[[3]]
testNames<-params[[4]]

sigma11<-tuningParameters[1]
C11<-tuningParameters[2]
sigma12<-tuningParameters[3]
C12<-tuningParameters[4]
sigma13<-tuningParameters[5]
C13<-tuningParameters[6]
sigma21<-tuningParameters[7]
C21<-tuningParameters[8]
sigma22<-tuningParameters[9]
C22<-tuningParameters[10]
sigma23<-tuningParameters[11]
C23<-tuningParameters[12]
sigma31<-tuningParameters[13]
C31<-tuningParameters[14]
sigma32<-tuningParameters[15]
C32<-tuningParameters[16]
sigma33<-tuningParameters[17]
C33<-tuningParameters[18]
sigma41<-tuningParameters[19]
C41<-tuningParameters[20]
sigma42<-tuningParameters[21]
C42<-tuningParameters[22]

#model based on CL11
m11<-FALSE
if(length(CL11)>0){
	m11<-TRUE
	d11<-DIST[(which(rownames(DIST) %in% CL11)),]
	d11<-as.data.frame(d11)
	tmp<-which(rownames(ALLDATA) %in% CL11)
	model11<-ALLDATA[tmp,]
	model11<-as.data.frame(model11)
}
#model based on CL12
m12<-FALSE
if(length(CL12)>0){
	m12<-TRUE
	d12<-DIST[(which(rownames(DIST) %in% CL12)),]
	d12<-as.data.frame(d12)
	tmp<-which(rownames(ALLDATA) %in% CL12)
	model12<-ALLDATA[tmp,]
	model12<-as.data.frame(model12)
}
#model based on CL13
m13<-FALSE
if(length(CL13)>0){
	m13<-TRUE
	d13<-DIST[(which(rownames(DIST) %in% CL13)),]
	d13<-as.data.frame(d13)
	tmp<-which(rownames(ALLDATA) %in% CL13)
	model13<-ALLDATA[tmp,]
	model13<-as.data.frame(model13)
}
#model based on CL21
m21<-FALSE
if(length(CL21)>0){
	m21<-TRUE
	d21<-DIST[(which(rownames(DIST) %in% CL21)),]
	d21<-as.data.frame(d21)
	tmp<-which(rownames(ALLDATA) %in% CL21)
	model21<-ALLDATA[tmp,]
	model21<-as.data.frame(model21)
}
#model based on CL22
m22<-FALSE
if(length(CL22)>0){
	m22<-TRUE
	d22<-DIST[(which(rownames(DIST) %in% CL22)),]
	d22<-as.data.frame(d22)
	tmp<-which(rownames(ALLDATA) %in% CL22)
	model22<-ALLDATA[tmp,]
	model22<-as.data.frame(model22)
}
#model based on CL23
m23<-FALSE
if(length(CL23)>0){
	m23<-TRUE
	d23<-DIST[(which(rownames(DIST) %in% CL23)),]
	d23<-as.data.frame(d23)
	tmp<-which(rownames(ALLDATA) %in% CL23)
	model23<-ALLDATA[tmp,]
	model23<-as.data.frame(model23)
}
#model based on CL31
m31<-FALSE
if(length(CL31)>0){
	m31<-TRUE
	d31<-DIST[(which(rownames(DIST) %in% CL31)),]
	d31<-as.data.frame(d31)
	tmp<-which(rownames(ALLDATA) %in% CL31)
	model31<-ALLDATA[tmp,]
	model31<-as.data.frame(model31)
}
#model based on CL32
m32<-FALSE
if(length(CL32)>0){
	m32<-TRUE
	d32<-DIST[(which(rownames(DIST) %in% CL32)),]
	d32<-as.data.frame(d32)
	tmp<-which(rownames(ALLDATA) %in% CL32)
	model32<-ALLDATA[tmp,]
	model32<-as.data.frame(model32)
}
#model based on CL33
m33<-FALSE
if(length(CL33)>0){
	m33<-TRUE
	d33<-DIST[(which(rownames(DIST) %in% CL33)),]
	d33<-as.data.frame(d33)
	tmp<-which(rownames(ALLDATA) %in% CL33)
	model33<-ALLDATA[tmp,]
	model33<-as.data.frame(model33)
}
#model based on CL41
m41<-FALSE
if(length(CL41)>0){
	m41<-TRUE
	d41<-DIST[(which(rownames(DIST) %in% CL41)),]
	d41<-as.data.frame(d41)
	tmp<-which(rownames(ALLDATA) %in% CL41)
	model41<-ALLDATA[tmp,]
	model41<-as.data.frame(model41)
}
#model based on CL42
m42<-FALSE
if(length(CL42)>0){
	m42<-TRUE
	d42<-DIST[(which(rownames(DIST) %in% CL42)),]
	d42<-as.data.frame(d42)
	tmp<-which(rownames(ALLDATA) %in% CL42)
	model42<-ALLDATA[tmp,]
	model42<-as.data.frame(model42)
}

MINSAMPLES<-10

Train_r2_svmB<-c()
Train_mse_svmB<-c()
Test_r2_svmB<-c()
Test_mse_svmB<-c()

testIndx<-which(rownames(ALLDATA) %in% testNames)
trainIndx<-which(rownames(ALLDATA) %in% trainNames)
test_normal<-ALLDATA[testIndx,]
test_normal<-as.data.frame(test_normal)
train_normal<-ALLDATA[trainIndx,]
train_normal<-as.data.frame(train_normal)


ix11=-1
if(m11) {
	ix11<-which(rownames(model11) %in% trainNames)
	if(length(ix11)==0) ix11=-1
}
created11<-FALSE #model created or not
if(m11){
	if(length(ix11)>MINSAMPLES){
		created11<-TRUE
		train11 = model11[ix11, ]
		svm11 <- train(as.formula(formula), data = train11, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma11, C=C11))
	}
}

ix12=-1
if(m12) {
	ix12<-which(rownames(model12) %in% trainNames)
	if(length(ix12)==0) ix12=-1
}
created12<-FALSE #model created or not
if(m12){
	if(length(ix12)>MINSAMPLES){
		created12<-TRUE
		train12 = model12[ix12, ]
		svm12 <- train(as.formula(formula), data = train12, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma12, C=C12))
	}
}

ix13=-1
if(m13) {
	ix13<-which(rownames(model13) %in% trainNames)
	if(length(ix13)==0) ix13=-1
}
created13<-FALSE #model created or not
if(m13){
	if(length(ix13)>MINSAMPLES){
		created13<-TRUE
		train13 = model13[ix13, ]
		svm13 <- train(as.formula(formula), data = train13, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma13, C=C13))
	}
}

ix21=-1
if(m21) {
	ix21<-which(rownames(model21) %in% trainNames)
	if(length(ix21)==0) ix21=-1
}
created21<-FALSE #model created or not
if(m21){
	if(length(ix21)>MINSAMPLES){
		created21<-TRUE
		train21 = model21[ix21, ]
		svm21 <- train(as.formula(formula), data = train21, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma21, C=C21))
	}
}

ix22=-1
if(m22) {
	ix22<-which(rownames(model22) %in% trainNames)
	if(length(ix22)==0) ix22=-1
}
created22<-FALSE #model created or not
if(m22){
	if(length(ix22)>MINSAMPLES){
		created22<-TRUE
		train22 = model22[ix22, ]
		svm22 <- train(as.formula(formula), data = train22, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma22, C=C22))
	}
}

ix23=-1
if(m23) {
	ix23<-which(rownames(model23) %in% trainNames)
	if(length(ix23)==0) ix23=-1
}
created23<-FALSE #model created or not
if(m23){
	if(length(ix23)>MINSAMPLES){
		created23<-TRUE
		train23 = model23[ix23, ]
		svm23 <- train(as.formula(formula), data = train23, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma23, C=C23))
	}
}

ix31=-1
if(m31) {
	ix31<-which(rownames(model31) %in% trainNames)
	if(length(ix31)==0) ix31=-1
}
created31<-FALSE #model created or not
if(m31){
	if(length(ix31)>MINSAMPLES){
		created31<-TRUE
		train31 = model31[ix31, ]
		svm31 <- train(as.formula(formula), data = train31, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma31, C=C31))
	}
}

ix32=-1
if(m32) {
	ix32<-which(rownames(model32) %in% trainNames)
	if(length(ix32)==0) ix32=-1
}
created32<-FALSE #model created or not
if(m32){
	if(length(ix32)>MINSAMPLES){
		created32<-TRUE
		train32 = model32[ix32, ]
		svm32 <- train(as.formula(formula), data = train32, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma32, C=C32))
	}
}

ix33=-1
if(m33) {
	ix33<-which(rownames(model33) %in% trainNames)
	if(length(ix33)==0) ix33=-1
}
created33<-FALSE #model created or not
if(m33){
	if(length(ix33)>MINSAMPLES){
		created33<-TRUE
		train33 = model33[ix33, ]
		svm33 <- train(as.formula(formula), data = train33, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma33, C=C33))
	}
}

ix41=-1
if(m41) {
	ix41<-which(rownames(model41) %in% trainNames)
	if(length(ix41)==0) ix41=-1
}
created41<-FALSE #model created or not
if(m41){
	if(length(ix41)>MINSAMPLES){
		created41<-TRUE
		train41 = model41[ix41, ]
		svm41 <- train(as.formula(formula), data = train41, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma41, C=C41))
	}
}

ix42=-1
if(m42) {
	ix42<-which(rownames(model42) %in% trainNames)
	if(length(ix42)==0) ix42=-1
}
created42<-FALSE #model created or not
if(m42){
	if(length(ix42)>MINSAMPLES){
		created42<-TRUE
		train42 = model42[ix42, ]
		svm42 <- train(as.formula(formula), data = train42, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma42, C=C42))
	}
}


###########################train_normal######################

L<-nrow(train_normal)

#vector containing the final prediction values
predTrain<-c()

if(DEBUG) {
	L=5
	print('TRAINING DATA')
}
train_index<-1

for(train_index in 1:L){

	predTrain<-c(predTrain,SVMEnsemble_11_howtopredict(SELECTION,train_normal,train_index,y,yName,d11,created11,model11,svm11,d12,created12,model12,svm12,d13,created13,model13,svm13,d21,created21,model21,svm21,d22,created22,model22,svm22,d23,created23,model23,svm23,d31,created31,model31,svm31,d32,created32,model32,svm32,d33,created33,model33,svm33,d41,created41,model41,svm41,d42,created42,model42,svm42))

} #train_index

predTrain<-as.numeric(predTrain)

mse_trtmp<-MSE(train_normal[1:L,ncol(train_normal)],predTrain)

Train_mse_svmB = c(Train_mse_svmB,mse_trtmp)

###########################train_normal######################

###########################test_normal######################

L<-nrow(test_normal)

#vector containing the final prediction values
predTest<-c()

if(DEBUG) {
	L=5
	print('TESTING DATA')
}
test_index<-1

for(test_index in 1:L){

	predTest<-c(predTest,SVMEnsemble_11_howtopredict(SELECTION,test_normal,test_index,y,yName,d11,created11,model11,svm11,d12,created12,model12,svm12,d13,created13,model13,svm13,d21,created21,model21,svm21,d22,created22,model22,svm22,d23,created23,model23,svm23,d31,created31,model31,svm31,d32,created32,model32,svm32,d33,created33,model33,svm33,d41,created41,model41,svm41,d42,created42,model42,svm42))

} #test_index

predTest<-as.numeric(predTest)

mse_tmp<-MSE(test_normal[1:L,ncol(test_normal)],predTest)

Test_mse_svmB = c(Test_mse_svmB,mse_tmp)

###########################test_normal######################

print(paste(' Train_mse: ',mse_trtmp,' Test_mse: ',mse_tmp,' Avg_Train_Test_mse: ',mean(c(mse_trtmp,mse_tmp)),sep = '')) ##

if(mean(c(mse_trtmp,mse_tmp))==params[[1]][2]) print("Replication SUCCESS!!") ##

} #end SVMEnsemble_Replicate()



SVMEnsemble_11_Predict<-function(params,blocks,TEST,SELECTION,DEBUG,ALLDATA,DIST,y,yName){

if(DEBUG){
	print(drug_index)
	print(drug_names[drug_index])
}

TUNELENGTH<-10 

CL11<-blocks[[1]]
CL12<-blocks[[2]]
CL13<-blocks[[3]]
CL21<-blocks[[4]]
CL22<-blocks[[5]]
CL23<-blocks[[6]]
CL31<-blocks[[7]]
CL32<-blocks[[8]]
CL33<-blocks[[9]]
CL41<-blocks[[10]]
CL42<-blocks[[11]]

tuningParameters<-params[[2]]

trainNames<-params[[3]]
testNames<-params[[4]]

sigma11<-tuningParameters[1]
C11<-tuningParameters[2]
sigma12<-tuningParameters[3]
C12<-tuningParameters[4]
sigma13<-tuningParameters[5]
C13<-tuningParameters[6]
sigma21<-tuningParameters[7]
C21<-tuningParameters[8]
sigma22<-tuningParameters[9]
C22<-tuningParameters[10]
sigma23<-tuningParameters[11]
C23<-tuningParameters[12]
sigma31<-tuningParameters[13]
C31<-tuningParameters[14]
sigma32<-tuningParameters[15]
C32<-tuningParameters[16]
sigma33<-tuningParameters[17]
C33<-tuningParameters[18]
sigma41<-tuningParameters[19]
C41<-tuningParameters[20]
sigma42<-tuningParameters[21]
C42<-tuningParameters[22]

#model based on CL11
m11<-FALSE
if(length(CL11)>0){
	m11<-TRUE
	d11<-DIST[(which(rownames(DIST) %in% CL11)),]
	d11<-as.data.frame(d11)
	tmp<-which(rownames(ALLDATA) %in% CL11)
	model11<-ALLDATA[tmp,]
	model11<-as.data.frame(model11)
}
#model based on CL12
m12<-FALSE
if(length(CL12)>0){
	m12<-TRUE
	d12<-DIST[(which(rownames(DIST) %in% CL12)),]
	d12<-as.data.frame(d12)
	tmp<-which(rownames(ALLDATA) %in% CL12)
	model12<-ALLDATA[tmp,]
	model12<-as.data.frame(model12)
}
#model based on CL13
m13<-FALSE
if(length(CL13)>0){
	m13<-TRUE
	d13<-DIST[(which(rownames(DIST) %in% CL13)),]
	d13<-as.data.frame(d13)
	tmp<-which(rownames(ALLDATA) %in% CL13)
	model13<-ALLDATA[tmp,]
	model13<-as.data.frame(model13)
}
#model based on CL21
m21<-FALSE
if(length(CL21)>0){
	m21<-TRUE
	d21<-DIST[(which(rownames(DIST) %in% CL21)),]
	d21<-as.data.frame(d21)
	tmp<-which(rownames(ALLDATA) %in% CL21)
	model21<-ALLDATA[tmp,]
	model21<-as.data.frame(model21)
}
#model based on CL22
m22<-FALSE
if(length(CL22)>0){
	m22<-TRUE
	d22<-DIST[(which(rownames(DIST) %in% CL22)),]
	d22<-as.data.frame(d22)
	tmp<-which(rownames(ALLDATA) %in% CL22)
	model22<-ALLDATA[tmp,]
	model22<-as.data.frame(model22)
}
#model based on CL23
m23<-FALSE
if(length(CL23)>0){
	m23<-TRUE
	d23<-DIST[(which(rownames(DIST) %in% CL23)),]
	d23<-as.data.frame(d23)
	tmp<-which(rownames(ALLDATA) %in% CL23)
	model23<-ALLDATA[tmp,]
	model23<-as.data.frame(model23)
}
#model based on CL31
m31<-FALSE
if(length(CL31)>0){
	m31<-TRUE
	d31<-DIST[(which(rownames(DIST) %in% CL31)),]
	d31<-as.data.frame(d31)
	tmp<-which(rownames(ALLDATA) %in% CL31)
	model31<-ALLDATA[tmp,]
	model31<-as.data.frame(model31)
}
#model based on CL32
m32<-FALSE
if(length(CL32)>0){
	m32<-TRUE
	d32<-DIST[(which(rownames(DIST) %in% CL32)),]
	d32<-as.data.frame(d32)
	tmp<-which(rownames(ALLDATA) %in% CL32)
	model32<-ALLDATA[tmp,]
	model32<-as.data.frame(model32)
}
#model based on CL33
m33<-FALSE
if(length(CL33)>0){
	m33<-TRUE
	d33<-DIST[(which(rownames(DIST) %in% CL33)),]
	d33<-as.data.frame(d33)
	tmp<-which(rownames(ALLDATA) %in% CL33)
	model33<-ALLDATA[tmp,]
	model33<-as.data.frame(model33)
}
#model based on CL41
m41<-FALSE
if(length(CL41)>0){
	m41<-TRUE
	d41<-DIST[(which(rownames(DIST) %in% CL41)),]
	d41<-as.data.frame(d41)
	tmp<-which(rownames(ALLDATA) %in% CL41)
	model41<-ALLDATA[tmp,]
	model41<-as.data.frame(model41)
}
#model based on CL42
m42<-FALSE
if(length(CL42)>0){
	m42<-TRUE
	d42<-DIST[(which(rownames(DIST) %in% CL42)),]
	d42<-as.data.frame(d42)
	tmp<-which(rownames(ALLDATA) %in% CL42)
	model42<-ALLDATA[tmp,]
	model42<-as.data.frame(model42)
}

MINSAMPLES<-10

Train_r2_svmB<-c()
Train_mse_svmB<-c()
Test_r2_svmB<-c()
Test_mse_svmB<-c()

trainIndx<-which(rownames(ALLDATA) %in% trainNames)
train_normal<-ALLDATA[trainIndx,]
train_normal<-as.data.frame(train_normal)


ix11=-1
if(m11) {
	ix11<-which(rownames(model11) %in% trainNames)
	if(length(ix11)==0) ix11=-1
}
created11<-FALSE #model created or not
if(m11){
	if(length(ix11)>MINSAMPLES){
		created11<-TRUE
		train11 = model11[ix11, ]
		svm11 <- train(as.formula(formula), data = train11, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma11, C=C11))
	}
}

ix12=-1
if(m12) {
	ix12<-which(rownames(model12) %in% trainNames)
	if(length(ix12)==0) ix12=-1
}
created12<-FALSE #model created or not
if(m12){
	if(length(ix12)>MINSAMPLES){
		created12<-TRUE
		train12 = model12[ix12, ]
		svm12 <- train(as.formula(formula), data = train12, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma12, C=C12))
	}
}

ix13=-1
if(m13) {
	ix13<-which(rownames(model13) %in% trainNames)
	if(length(ix13)==0) ix13=-1
}
created13<-FALSE #model created or not
if(m13){
	if(length(ix13)>MINSAMPLES){
		created13<-TRUE
		train13 = model13[ix13, ]
		svm13 <- train(as.formula(formula), data = train13, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma13, C=C13))
	}
}

ix21=-1
if(m21) {
	ix21<-which(rownames(model21) %in% trainNames)
	if(length(ix21)==0) ix21=-1
}
created21<-FALSE #model created or not
if(m21){
	if(length(ix21)>MINSAMPLES){
		created21<-TRUE
		train21 = model21[ix21, ]
		svm21 <- train(as.formula(formula), data = train21, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma21, C=C21))
	}
}

ix22=-1
if(m22) {
	ix22<-which(rownames(model22) %in% trainNames)
	if(length(ix22)==0) ix22=-1
}
created22<-FALSE #model created or not
if(m22){
	if(length(ix22)>MINSAMPLES){
		created22<-TRUE
		train22 = model22[ix22, ]
		svm22 <- train(as.formula(formula), data = train22, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma22, C=C22))
	}
}

ix23=-1
if(m23) {
	ix23<-which(rownames(model23) %in% trainNames)
	if(length(ix23)==0) ix23=-1
}
created23<-FALSE #model created or not
if(m23){
	if(length(ix23)>MINSAMPLES){
		created23<-TRUE
		train23 = model23[ix23, ]
		svm23 <- train(as.formula(formula), data = train23, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma23, C=C23))
	}
}

ix31=-1
if(m31) {
	ix31<-which(rownames(model31) %in% trainNames)
	if(length(ix31)==0) ix31=-1
}
created31<-FALSE #model created or not
if(m31){
	if(length(ix31)>MINSAMPLES){
		created31<-TRUE
		train31 = model31[ix31, ]
		svm31 <- train(as.formula(formula), data = train31, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma31, C=C31))
	}
}

ix32=-1
if(m32) {
	ix32<-which(rownames(model32) %in% trainNames)
	if(length(ix32)==0) ix32=-1
}
created32<-FALSE #model created or not
if(m32){
	if(length(ix32)>MINSAMPLES){
		created32<-TRUE
		train32 = model32[ix32, ]
		svm32 <- train(as.formula(formula), data = train32, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma32, C=C32))
	}
}

ix33=-1
if(m33) {
	ix33<-which(rownames(model33) %in% trainNames)
	if(length(ix33)==0) ix33=-1
}
created33<-FALSE #model created or not
if(m33){
	if(length(ix33)>MINSAMPLES){
		created33<-TRUE
		train33 = model33[ix33, ]
		svm33 <- train(as.formula(formula), data = train33, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma33, C=C33))
	}
}

ix41=-1
if(m41) {
	ix41<-which(rownames(model41) %in% trainNames)
	if(length(ix41)==0) ix41=-1
}
created41<-FALSE #model created or not
if(m41){
	if(length(ix41)>MINSAMPLES){
		created41<-TRUE
		train41 = model41[ix41, ]
		svm41 <- train(as.formula(formula), data = train41, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma41, C=C41))
	}
}

ix42=-1
if(m42) {
	ix42<-which(rownames(model42) %in% trainNames)
	if(length(ix42)==0) ix42=-1
}
created42<-FALSE #model created or not
if(m42){
	if(length(ix42)>MINSAMPLES){
		created42<-TRUE
		train42 = model42[ix42, ]
		svm42 <- train(as.formula(formula), data = train42, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma42, C=C42))
	}
}



test_normal<-TEST

###########################test_normal######################

L<-nrow(test_normal)

#vector containing the final prediction values
predTest<-c()

if(DEBUG) {
	L=5
	print('TESTING DATA')
}
test_index<-1

for(test_index in 1:L){

	predTest<-c(predTest,SVMEnsemble_11_howtopredict(SELECTION,test_normal,test_index,y,yName,d11,created11,model11,svm11,d12,created12,model12,svm12,d13,created13,model13,svm13,d21,created21,model21,svm21,d22,created22,model22,svm22,d23,created23,model23,svm23,d31,created31,model31,svm31,d32,created32,model32,svm32,d33,created33,model33,svm33,d41,created41,model41,svm41,d42,created42,model42,svm42))

} #test_index

predTest<-as.numeric(predTest)

###########################test_normal######################

predTest

} #end SVMEnsemble_11_Predict()
