#Code generated by RScriptGenerator.java


SVMEnsemble_2_howtopredict<-function(SELECTION,test_normal,test_index,y,yName,d11,created11,model11,svm11,d12,created12,model12,svm12){

if(DEBUG){
	print(test_index)
	print(rownames(test_normal)[test_index])
}

#get PC1 value.
tpc1<-y[which(yName==rownames(test_normal)[test_index])]
prd<-0 

if(DEBUG) print(tpc1)


#RADs<-c(100,200,300,400)
RADs<-c(abs(max(d11$auc)-min(d11$auc))/2,abs(max(d12$auc)-min(d12$auc))/2)
if(DEBUG) print(paste('rad11','rad12',sep=' '))
if(DEBUG) print(RADs)
RADs<-sort(RADs)
radius<-RADs[1]
if(DEBUG) print(radius)
RAD<-radius
nbr11<-0
pred11<-0
radius11<-0
bsc11<-0 #block spearman correlation
if(created11){
	pred11 = predict(svm11, test_normal[test_index,])
	pred11 = as.numeric(pred11)
	tmp11<-rbind(d11,c(pred11,tpc1))
	tmp11<-as.data.frame(tmp11)
	dist11<-dist(tmp11, method = "euclidean")
	dist11<-as.matrix(dist11)
	tmp111<-t(rbind(model11[,-ncol(model11)],test_normal[test_index,-ncol(test_normal)])) #transpose
	cor11<-cor(tmp111, method = c('spearman'))
	bsc11<-sum(cor11[1:nrow(cor11)-1,ncol(cor11)])/nrow(d11)
}
mc11<-0
if(created11) {
	found<-which(dist11[1:nrow(dist11)-1,ncol(dist11)]<=RAD)
	neighbors11<-rownames(dist11)[found]
	nbr11<-length(found)
	if(nbr11>0){
		corIndx<-which(rownames(cor11) %in% neighbors11)   #we will look at the last column of the matrix. So matching by rownames
		mc11<-mean(cor11[corIndx,ncol(cor11)])
		if(DEBUG){
			print("svm11")
			print(neighbors11)
			print(rownames(cor11)[corIndx])
		}
	} else {
		mc11<-0
	}
}
nbr12<-0
pred12<-0
radius12<-0
bsc12<-0 #block spearman correlation
if(created12){
	pred12 = predict(svm12, test_normal[test_index,])
	pred12 = as.numeric(pred12)
	tmp12<-rbind(d12,c(pred12,tpc1))
	tmp12<-as.data.frame(tmp12)
	dist12<-dist(tmp12, method = "euclidean")
	dist12<-as.matrix(dist12)
	tmp121<-t(rbind(model12[,-ncol(model12)],test_normal[test_index,-ncol(test_normal)])) #transpose
	cor12<-cor(tmp121, method = c('spearman'))
	bsc12<-sum(cor12[1:nrow(cor12)-1,ncol(cor12)])/nrow(d12)
}
mc12<-0
if(created12) {
	found<-which(dist12[1:nrow(dist12)-1,ncol(dist12)]<=RAD)
	neighbors12<-rownames(dist12)[found]
	nbr12<-length(found)
	if(nbr12>0){
		corIndx<-which(rownames(cor12) %in% neighbors12)   #we will look at the last column of the matrix. So matching by rownames
		mc12<-mean(cor12[corIndx,ncol(cor12)])
		if(DEBUG){
			print("svm12")
			print(neighbors12)
			print(rownames(cor12)[corIndx])
		}
	} else {
		mc12<-0
	}
}
path<-"/Users/maju06/Documents/OSUMC/3C/"
if(DEBUG){
	blank<-c(1,2,3)
	blank<-as.data.frame(blank)
	colnames(blank)<-'x'
	blank$y<-c(1,2,3)
	blank<-as.data.frame(blank)
	if(!is.null(tmp11)){
		df11<-tmp11
		df11$label<-'old'
		df11$label[nrow(tmp11)]<-'new'
		df11<-as.data.frame(df11)
		p11<-ggplot(df11, aes(auc,pc1, color=factor(label))) + geom_point() + theme_classic()
	} else p11<-ggplot(blank, aes(x,y)) + theme_classic()
	if(!is.null(tmp12)){
		df12<-tmp12
		df12$label<-'old'
		df12$label[nrow(tmp12)]<-'new'
		df12<-as.data.frame(df12)
		p12<-ggplot(df12, aes(auc,pc1, color=factor(label))) + geom_point() + theme_classic()
	} else p12<-ggplot(blank, aes(x,y)) + theme_classic()
	png(filename = paste(path,"SVE_2_DEBUG_testIndex",test_index,".png",sep=""), width = 10, height = 10, units = "in", res = 200)
	plot_grid(p11,p12,ncol = 3, labels = "AUTO", label_size = 16)
	dev.off()
}
MC<-c(mc11,mc12)
NBR<-c(nbr11,nbr12)
PRED<-c(pred11,pred12)
BSC<-c(bsc11,bsc12)
if(DEBUG) {
	print(paste('pred11:',pred11,' nbr11:',nbr11,' mc11:',mc11,' bsc11:',bsc11,sep=''))
	print(paste('pred12:',pred12,' nbr12:',nbr12,' mc12:',mc12,' bsc12:',bsc12,sep=''))
}
sumNbr<-sum(NBR)
if(SELECTION==0){
	maxIndx<-which(BSC==max(BSC))[1]
	prd<-PRED[maxIndx]
} else {
	r<-2
	while(sumNbr==0 && r<=2){   ##the case where such a radius is chosen that all meanCorrelation values is 0
	radius<-RADs[r]
	r<-r+1
	if(DEBUG) print(radius)
	RAD<-radius
	nbr11<-0
	pred11<-0
	radius11<-0
	bsc11<-0 #block spearman correlation
	if(created11){
		pred11 = predict(svm11, test_normal[test_index,])
		pred11 = as.numeric(pred11)
		tmp11<-rbind(d11,c(pred11,tpc1))
		tmp11<-as.data.frame(tmp11)
		dist11<-dist(tmp11, method = "euclidean")
		dist11<-as.matrix(dist11)
		tmp111<-t(rbind(model11[,-ncol(model11)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor11<-cor(tmp111, method = c('spearman'))
		bsc11<-sum(cor11[1:nrow(cor11)-1,ncol(cor11)])/nrow(d11)
	}
	mc11<-0
	if(created11) {
		found<-which(dist11[1:nrow(dist11)-1,ncol(dist11)]<=RAD)
		neighbors11<-rownames(dist11)[found]
		nbr11<-length(found)
		if(nbr11>0){
			corIndx<-which(rownames(cor11) %in% neighbors11)   #we will look at the last column of the matrix. So matching by rownames
			mc11<-mean(cor11[corIndx,ncol(cor11)])
			if(DEBUG){
				print("svm11")
				print(neighbors11)
				print(rownames(cor11)[corIndx])
			}
		} else {
			mc11<-0
		}
	}
	nbr12<-0
	pred12<-0
	radius12<-0
	bsc12<-0 #block spearman correlation
	if(created12){
		pred12 = predict(svm12, test_normal[test_index,])
		pred12 = as.numeric(pred12)
		tmp12<-rbind(d12,c(pred12,tpc1))
		tmp12<-as.data.frame(tmp12)
		dist12<-dist(tmp12, method = "euclidean")
		dist12<-as.matrix(dist12)
		tmp121<-t(rbind(model12[,-ncol(model12)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor12<-cor(tmp121, method = c('spearman'))
		bsc12<-sum(cor12[1:nrow(cor12)-1,ncol(cor12)])/nrow(d12)
	}
	mc12<-0
	if(created12) {
		found<-which(dist12[1:nrow(dist12)-1,ncol(dist12)]<=RAD)
		neighbors12<-rownames(dist12)[found]
		nbr12<-length(found)
		if(nbr12>0){
			corIndx<-which(rownames(cor12) %in% neighbors12)   #we will look at the last column of the matrix. So matching by rownames
			mc12<-mean(cor12[corIndx,ncol(cor12)])
			if(DEBUG){
				print("svm12")
				print(neighbors12)
				print(rownames(cor12)[corIndx])
			}
		} else {
			mc12<-0
		}
	}
	MC<-c(mc11,mc12)
	NBR<-c(nbr11,nbr12)
	PRED<-c(pred11,pred12)
	sumNbr<-sum(NBR)
	if(DEBUG) {
		print(paste('pred11:',pred11,' nbr11:',nbr11,' mc11:',mc11,sep=''))
		print(paste('pred12:',pred12,' nbr12:',nbr12,' mc12:',mc12,sep=''))
	}
	} ##while  #going through the RADs vector one by one
	#still no neighbors
	if(sumNbr==0){
	RAD<-500
	nbr11<-0
	pred11<-0
	radius11<-0
	bsc11<-0 #block spearman correlation
	if(created11){
		pred11 = predict(svm11, test_normal[test_index,])
		pred11 = as.numeric(pred11)
		tmp11<-rbind(d11,c(pred11,tpc1))
		tmp11<-as.data.frame(tmp11)
		dist11<-dist(tmp11, method = "euclidean")
		dist11<-as.matrix(dist11)
		tmp111<-t(rbind(model11[,-ncol(model11)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor11<-cor(tmp111, method = c('spearman'))
		bsc11<-sum(cor11[1:nrow(cor11)-1,ncol(cor11)])/nrow(d11)
	}
	mc11<-0
	if(created11) {
		found<-which(dist11[1:nrow(dist11)-1,ncol(dist11)]<=RAD)
		neighbors11<-rownames(dist11)[found]
		nbr11<-length(found)
		if(nbr11>0){
			corIndx<-which(rownames(cor11) %in% neighbors11)   #we will look at the last column of the matrix. So matching by rownames
			mc11<-mean(cor11[corIndx,ncol(cor11)])
			if(DEBUG){
				print("svm11")
				print(neighbors11)
				print(rownames(cor11)[corIndx])
			}
		} else {
			mc11<-0
		}
	}
	nbr12<-0
	pred12<-0
	radius12<-0
	bsc12<-0 #block spearman correlation
	if(created12){
		pred12 = predict(svm12, test_normal[test_index,])
		pred12 = as.numeric(pred12)
		tmp12<-rbind(d12,c(pred12,tpc1))
		tmp12<-as.data.frame(tmp12)
		dist12<-dist(tmp12, method = "euclidean")
		dist12<-as.matrix(dist12)
		tmp121<-t(rbind(model12[,-ncol(model12)],test_normal[test_index,-ncol(test_normal)])) #transpose
		cor12<-cor(tmp121, method = c('spearman'))
		bsc12<-sum(cor12[1:nrow(cor12)-1,ncol(cor12)])/nrow(d12)
	}
	mc12<-0
	if(created12) {
		found<-which(dist12[1:nrow(dist12)-1,ncol(dist12)]<=RAD)
		neighbors12<-rownames(dist12)[found]
		nbr12<-length(found)
		if(nbr12>0){
			corIndx<-which(rownames(cor12) %in% neighbors12)   #we will look at the last column of the matrix. So matching by rownames
			mc12<-mean(cor12[corIndx,ncol(cor12)])
			if(DEBUG){
				print("svm12")
				print(neighbors12)
				print(rownames(cor12)[corIndx])
			}
		} else {
			mc12<-0
		}
	}
	MC<-c(mc11,mc12)
	NBR<-c(nbr11,nbr12)
	PRED<-c(pred11,pred12)
	sumNbr<-sum(NBR)
	if(DEBUG) {
		print(paste('pred11:',pred11,' nbr11:',nbr11,' mc11:',mc11,sep=''))
		print(paste('pred12:',pred12,' nbr12:',nbr12,' mc12:',mc12,sep=''))
	}
	}#using radius = 500
} ##SELECTION!=0
if(SELECTION==1){
	maxIndx<-which(MC==max(MC))[1]
	prd<-PRED[maxIndx]
} else if(SELECTION==2){
	wMC<-MC/sum(MC)
	prd<-sum(wMC*PRED)
} else if(SELECTION==3){
	maxIndx<-which(NBR==max(NBR))[1]
	prd<-PRED[maxIndx]
} else if(SELECTION==4){
	wNb<-NBR/sum(NBR)
	prd<-sum(wNb*PRED)
}
if(DEBUG) print(paste("SELECTION:",SELECTION," real: ",test_normal[test_index,ncol(test_normal)]," prd: ",prd, sep = ''))
prd
} #end SVMEnsemble_2_howtopredict()




SVMEnsemble_2<-function(blocks,percTesting,SELECTION,fold,N,CV,DEBUG,ALLDATA,DIST,y,yName,PATH){

if(DEBUG){
	print(drug_index)
	print(drug_names[drug_index])
}

cv_sse<-0

TUNELENGTH<-10 

CL11<-blocks[[1]]
CL12<-blocks[[2]]

#model based on CL11
m11<-FALSE
if(length(CL11)>0){
	m11<-TRUE
	d11<-DIST[(which(rownames(DIST) %in% CL11)),]
	d11<-as.data.frame(d11)
	tmp<-which(rownames(ALLDATA) %in% CL11)
	model11<-ALLDATA[tmp,]
	model11<-as.data.frame(model11)
}
#model based on CL12
m12<-FALSE
if(length(CL12)>0){
	m12<-TRUE
	d12<-DIST[(which(rownames(DIST) %in% CL12)),]
	d12<-as.data.frame(d12)
	tmp<-which(rownames(ALLDATA) %in% CL12)
	model12<-ALLDATA[tmp,]
	model12<-as.data.frame(model12)
}

MINSAMPLES<-10

if(DEBUG) print(drug_names[drug_index])
formula = paste(drug_names[drug_index], '~.', sep = '')

bSigma11=-1
bC11=-1
bSigma12=-1
bC12=-1

bestMSE=999999

edgeIndices<-getFoldIndices(length(yName),fold)

Train_r2_svmB<-c()
Train_mse_svmB<-c()
Test_r2_svmB<-c()
Test_mse_svmB<-c()
firstCol<-c()
Avg_testtrain<-c()

if(CV==0) repetitions = fold else repetitions = N

firstCol<-c(1:repetitions)

f<-1
for(f in 1:repetitions){

if(DEBUG) print(paste('fold/iteration: ',f,sep = '')) 

if(CV==0){  #normal cross-validation
	testNames<-yName[edgeIndices[[f]]]
	trainNames<-yName[-edgeIndices[[f]]]
} else { # repeated crossvalidation
	test<-sample(1:length(yName), percTesting*length(yName))
	testNames<-yName[test]
	trainNames<-yName[-test]
}

testIndx<-which(rownames(ALLDATA) %in% testNames)
trainIndx<-which(rownames(ALLDATA) %in% trainNames)
test_normal<-ALLDATA[testIndx,]
test_normal<-as.data.frame(test_normal)
train_normal<-ALLDATA[trainIndx,]
train_normal<-as.data.frame(train_normal)

ix11=-1
if(m11) {
	ix11<-which(rownames(model11) %in% trainNames)
	if(length(ix11)==0) ix11=-1
}
sigma11=-1
C11=-1

ix12=-1
if(m12) {
	ix12<-which(rownames(model12) %in% trainNames)
	if(length(ix12)==0) ix12=-1
}
sigma12=-1
C12=-1


created11<-FALSE #model created or not
if(m11){
	if(length(ix11)>MINSAMPLES){
		created11<-TRUE
		train11 = model11[ix11, ]
		svm11 <- train(as.formula(formula), data = train11, method = "svmRadial", tuneLength = 10)
		sigma11<-svm11$bestTune$sigma
		C11<-svm11$bestTune$C
	}
}
created12<-FALSE #model created or not
if(m12){
	if(length(ix12)>MINSAMPLES){
		created12<-TRUE
		train12 = model12[ix12, ]
		svm12 <- train(as.formula(formula), data = train12, method = "svmRadial", tuneLength = 10)
		sigma12<-svm12$bestTune$sigma
		C12<-svm12$bestTune$C
	}
}

###########################train_normal######################

L<-nrow(train_normal)

#vector containing the final prediction values
predTrain<-c()

if(DEBUG) {
	L=5
	print('TRAINING DATA')
}
train_index<-1

for(train_index in 1:L){

	predTrain<-c(predTrain,SVMEnsemble_2_howtopredict(SELECTION,train_normal,train_index,y,yName,d11,created11,model11,svm11,d12,created12,model12,svm12))

} #train_index

predTrain<-as.numeric(predTrain)

mse_trtmp<-MSE(train_normal[1:L,ncol(train_normal)],predTrain)

sse_trtmp<-sum((train_normal[1:L,ncol(train_normal)]-predTrain)^2)

Train_mse_svmB = c(Train_mse_svmB,mse_trtmp)

###########################train_normal######################

###########################test_normal######################

L<-nrow(test_normal)

#vector containing the final prediction values
predTest<-c()

if(DEBUG) {
	L=5
	print('TESTING DATA')
}
test_index<-1

for(test_index in 1:L){

	predTest<-c(predTest,SVMEnsemble_2_howtopredict(SELECTION,test_normal,test_index,y,yName,d11,created11,model11,svm11,d12,created12,model12,svm12))

} #test_index

predTest<-as.numeric(predTest)

mse_tmp<-MSE(test_normal[1:L,ncol(test_normal)],predTest)

sse_tmp<-sum((test_normal[1:L,ncol(test_normal)]-predTest)^2)

cv_sse<-cv_sse + sum((test_normal[1:L,ncol(test_normal)]-predTest)^2)

Test_mse_svmB = c(Test_mse_svmB,mse_tmp)

###########################test_normal######################

Avg_testtrain<-c(Avg_testtrain,mean(c(mse_trtmp,mse_tmp)))

if(mean(c(mse_trtmp,mse_tmp))<bestMSE){
	bestMSE=mean(c(mse_trtmp,mse_tmp))

	bSigma11=sigma11
	bC11=C11
	bSigma12=sigma12
	bC12=C12
	trNames<-trainNames
	teNames<-testNames
}

print(paste('CV Fold/Iteration-',f,' Train_mse: ',mse_trtmp,' Test_mse: ',mse_tmp,' Avg_Train_Test_mse: ',mean(c(mse_trtmp,mse_tmp)),sep = ''))

} # cross-validation

tbw<-data.frame(firstCol,Train_mse_svmB,Test_mse_svmB,Avg_testtrain)
colnames(tbw)<-c('Iteration/Fold','Train_MSE','Test_MSE','Avg_Train_Test_MSE')
write.csv(tbw,paste(PATH,'SVMEnsemble_2_',drug_names[drug_index],'.csv',sep = ''), row.names = F, quote = F)

meanSqError<-mean(Avg_testtrain)

print(paste('Fitness','Avg_MSE',sep = ' '))
print(c(1/meanSqError,meanSqError))

print(paste('k=2_CV_RMSE',sqrt(cv_sse/nrow(ALLDATA)),sep=' '))

list(c(meanSqError,bestMSE),c(bSigma11,bC11,bSigma12,bC12),trNames,teNames)

} #end SVMEnsemble_2()



SVMEnsemble_2_Replicate<-function(params,blocks,SELECTION,DEBUG,ALLDATA,DIST,y,yName){

if(DEBUG){
	print(drug_index)
	print(drug_names[drug_index])
}

TUNELENGTH<-10 

CL11<-blocks[[1]]
CL12<-blocks[[2]]

tuningParameters<-params[[2]]

trainNames<-params[[3]]
testNames<-params[[4]]

sigma11<-tuningParameters[1]
C11<-tuningParameters[2]
sigma12<-tuningParameters[3]
C12<-tuningParameters[4]

#model based on CL11
m11<-FALSE
if(length(CL11)>0){
	m11<-TRUE
	d11<-DIST[(which(rownames(DIST) %in% CL11)),]
	d11<-as.data.frame(d11)
	tmp<-which(rownames(ALLDATA) %in% CL11)
	model11<-ALLDATA[tmp,]
	model11<-as.data.frame(model11)
}
#model based on CL12
m12<-FALSE
if(length(CL12)>0){
	m12<-TRUE
	d12<-DIST[(which(rownames(DIST) %in% CL12)),]
	d12<-as.data.frame(d12)
	tmp<-which(rownames(ALLDATA) %in% CL12)
	model12<-ALLDATA[tmp,]
	model12<-as.data.frame(model12)
}

MINSAMPLES<-10

Train_r2_svmB<-c()
Train_mse_svmB<-c()
Test_r2_svmB<-c()
Test_mse_svmB<-c()

testIndx<-which(rownames(ALLDATA) %in% testNames)
trainIndx<-which(rownames(ALLDATA) %in% trainNames)
test_normal<-ALLDATA[testIndx,]
test_normal<-as.data.frame(test_normal)
train_normal<-ALLDATA[trainIndx,]
train_normal<-as.data.frame(train_normal)


ix11=-1
if(m11) {
	ix11<-which(rownames(model11) %in% trainNames)
	if(length(ix11)==0) ix11=-1
}
created11<-FALSE #model created or not
if(m11){
	if(length(ix11)>MINSAMPLES){
		created11<-TRUE
		train11 = model11[ix11, ]
		svm11 <- train(as.formula(formula), data = train11, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma11, C=C11))
	}
}

ix12=-1
if(m12) {
	ix12<-which(rownames(model12) %in% trainNames)
	if(length(ix12)==0) ix12=-1
}
created12<-FALSE #model created or not
if(m12){
	if(length(ix12)>MINSAMPLES){
		created12<-TRUE
		train12 = model12[ix12, ]
		svm12 <- train(as.formula(formula), data = train12, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma12, C=C12))
	}
}


###########################train_normal######################

L<-nrow(train_normal)

#vector containing the final prediction values
predTrain<-c()

if(DEBUG) {
	L=5
	print('TRAINING DATA')
}
train_index<-1

for(train_index in 1:L){

	predTrain<-c(predTrain,SVMEnsemble_2_howtopredict(SELECTION,train_normal,train_index,y,yName,d11,created11,model11,svm11,d12,created12,model12,svm12))

} #train_index

predTrain<-as.numeric(predTrain)

mse_trtmp<-MSE(train_normal[1:L,ncol(train_normal)],predTrain)

Train_mse_svmB = c(Train_mse_svmB,mse_trtmp)

###########################train_normal######################

###########################test_normal######################

L<-nrow(test_normal)

#vector containing the final prediction values
predTest<-c()

if(DEBUG) {
	L=5
	print('TESTING DATA')
}
test_index<-1

for(test_index in 1:L){

	predTest<-c(predTest,SVMEnsemble_2_howtopredict(SELECTION,test_normal,test_index,y,yName,d11,created11,model11,svm11,d12,created12,model12,svm12))

} #test_index

predTest<-as.numeric(predTest)

mse_tmp<-MSE(test_normal[1:L,ncol(test_normal)],predTest)

Test_mse_svmB = c(Test_mse_svmB,mse_tmp)

###########################test_normal######################

print(paste(' Train_mse: ',mse_trtmp,' Test_mse: ',mse_tmp,' Avg_Train_Test_mse: ',mean(c(mse_trtmp,mse_tmp)),sep = '')) ##

if(mean(c(mse_trtmp,mse_tmp))==params[[1]][2]) print("Replication SUCCESS!!") ##

} #end SVMEnsemble_Replicate()



SVMEnsemble_2_Predict<-function(params,blocks,TEST,SELECTION,DEBUG,ALLDATA,DIST,y,yName){

if(DEBUG){
	print(drug_index)
	print(drug_names[drug_index])
}

TUNELENGTH<-10 

CL11<-blocks[[1]]
CL12<-blocks[[2]]

tuningParameters<-params[[2]]

trainNames<-params[[3]]
testNames<-params[[4]]

sigma11<-tuningParameters[1]
C11<-tuningParameters[2]
sigma12<-tuningParameters[3]
C12<-tuningParameters[4]

#model based on CL11
m11<-FALSE
if(length(CL11)>0){
	m11<-TRUE
	d11<-DIST[(which(rownames(DIST) %in% CL11)),]
	d11<-as.data.frame(d11)
	tmp<-which(rownames(ALLDATA) %in% CL11)
	model11<-ALLDATA[tmp,]
	model11<-as.data.frame(model11)
}
#model based on CL12
m12<-FALSE
if(length(CL12)>0){
	m12<-TRUE
	d12<-DIST[(which(rownames(DIST) %in% CL12)),]
	d12<-as.data.frame(d12)
	tmp<-which(rownames(ALLDATA) %in% CL12)
	model12<-ALLDATA[tmp,]
	model12<-as.data.frame(model12)
}

MINSAMPLES<-10

Train_r2_svmB<-c()
Train_mse_svmB<-c()
Test_r2_svmB<-c()
Test_mse_svmB<-c()

trainIndx<-which(rownames(ALLDATA) %in% trainNames)
train_normal<-ALLDATA[trainIndx,]
train_normal<-as.data.frame(train_normal)


ix11=-1
if(m11) {
	ix11<-which(rownames(model11) %in% trainNames)
	if(length(ix11)==0) ix11=-1
}
created11<-FALSE #model created or not
if(m11){
	if(length(ix11)>MINSAMPLES){
		created11<-TRUE
		train11 = model11[ix11, ]
		svm11 <- train(as.formula(formula), data = train11, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma11, C=C11))
	}
}

ix12=-1
if(m12) {
	ix12<-which(rownames(model12) %in% trainNames)
	if(length(ix12)==0) ix12=-1
}
created12<-FALSE #model created or not
if(m12){
	if(length(ix12)>MINSAMPLES){
		created12<-TRUE
		train12 = model12[ix12, ]
		svm12 <- train(as.formula(formula), data = train12, method = "svmRadial", tuneGrid = expand.grid(sigma=sigma12, C=C12))
	}
}



test_normal<-TEST

###########################test_normal######################

L<-nrow(test_normal)

#vector containing the final prediction values
predTest<-c()

if(DEBUG) {
	L=5
	print('TESTING DATA')
}
test_index<-1

for(test_index in 1:L){

	predTest<-c(predTest,SVMEnsemble_2_howtopredict(SELECTION,test_normal,test_index,y,yName,d11,created11,model11,svm11,d12,created12,model12,svm12))

} #test_index

predTest<-as.numeric(predTest)

###########################test_normal######################

predTest

} #end SVMEnsemble_2_Predict()
